
SELECT  ID, ACCEPT_TIME, TYPE, AMOUNT, CURRENCY_CODE , STATUS, NOTE1,CASH_BALANCE,COMPLETE_TIME,TABLE_FLAG   
FROM ( (  (
    SELECT  DEPOSIT_ID ID , DEPOSIT_ACCEPT_DATETIME ACCEPT_TIME ,  INPUT_TYPE TYPE , DEPOSIT_AMOUNT   AMOUNT , CURRENCY_CODE , STATUS, NOTE1 ,CUSTOMER_ID,CASH_BALANCE,ACCOUNT_DATETIME COMPLETE_TIME,1 TABLE_FLAG  
    FROM   JHF_DEPOSIT   WHERE ACTIVE_FLAG =  1 AND CUSTOMER_ID = '00001332'   ) 
    UNION  (
    SELECT  WITHDRAWAL_ID ID , WITHDRAWAL_ACCEPT_DATETIME ACCEPT_TIME ,  INPUT_TYPE TYPE , WITHDRAWAL_AMOUNT  AMOUNT , CURRENCY_CODE , STATUS, NOTE1 ,CUSTOMER_ID,CASH_BALANCE,WITHDRAWAL_COMPLETE_DATETIME COMPLETE_TIME,0 TABLE_FLAG  
    FROM   JHF_WITHDRAWAL  WHERE ACTIVE_FLAG =  1 AND CUSTOMER_ID = '00001332'   )    ) 
    ORDER BY ACCEPT_TIME desc ) CC   WHERE STATUS <> 2 and ( (TYPE + STATUS)<>0 )  
    ORDER BY ACCEPT_TIME DESC   limit  0 , 10 





select count(*) from (  
    SELECT  ID, ACCEPT_TIME, TYPE, AMOUNT, CURRENCY_CODE , STATUS, NOTE1,CASH_BALANCE,COMPLETE_TIME,TABLE_FLAG   
    FROM ( (  (
        SELECT  DEPOSIT_ID ID , DEPOSIT_ACCEPT_DATETIME ACCEPT_TIME ,  INPUT_TYPE TYPE , DEPOSIT_AMOUNT   AMOUNT , CURRENCY_CODE , STATUS, NOTE1 ,CUSTOMER_ID,CASH_BALANCE,ACCOUNT_DATETIME COMPLETE_TIME,1 TABLE_FLAG  
        FROM   JHF_DEPOSIT   WHERE ACTIVE_FLAG =  1 AND CUSTOMER_ID = '00001332'   ) 
        UNION  (
        SELECT  WITHDRAWAL_ID ID , WITHDRAWAL_ACCEPT_DATETIME ACCEPT_TIME ,  INPUT_TYPE TYPE , WITHDRAWAL_AMOUNT  AMOUNT , CURRENCY_CODE , STATUS, NOTE1 ,CUSTOMER_ID,CASH_BALANCE,WITHDRAWAL_COMPLETE_DATETIME COMPLETE_TIME,0 TABLE_FLAG  
        FROM   JHF_WITHDRAWAL  WHERE ACTIVE_FLAG =  1 AND CUSTOMER_ID = '00001332'   )    ) ORDER BY ACCEPT_TIME desc ) CC   WHERE STATUS <> 2 and ( (TYPE + STATUS)<>0 ) ) DD