
SELECT order_id,TOP_ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009092302289563';


SELECT order_id,TOP_ORDER_ID,ORDER_BIND_ID FROM JHF_ALIVE_ORDER WHERE TOP_ORDER_ID = '20090923ORD00619528';

UPDATE JHF_ALIVE_CONTRACT SET SETTLED_TYPE = 1 WHERE CONTRACT_ID = '20090923CONT00276515';

UPDATE JHF_ALIVE_CONTRACT SET SETTLED_TYPE = 1,
    SETTLEMENT_COMMISSION = (SELECT LOT_P6_COMMISSION  FROM JHF_COMMISSION_CONFIG WHERE  CURRENCY_PAIR = 'USD/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 1)  
WHERE CONTRACT_ID = '20090923CONT00276515';



 //============================
SELECT ORDER_ID,EXECUTION_ID,EXECUTION_AMOUNT ,COMMISSION,COMMISSION_TYPE FROM JHF_ALIVE_EXECUTION WHERE ORDER_ID IN (
    SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009110400288606'
);


--OPEN CONTRACT
SELECT ORDER_ID,CONTRACT_ID,OPEN_COMMISSION,SETTLEMENT_COMMISSION ,SETTLED_TYPE FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID IN (
    SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009110400288606'
);


--SETTLE CONTRACT
SELECT ORDER_ID,CONTRACT_ID,OPEN_COMMISSION,SETTLEMENT_COMMISSION ,SETTLED_TYPE,FORCE_RELATION_ID ,FORCE_RELATION_FLAG FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID IN (
    SELECT TOP_ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009110400288606'
);



SELECT CURRENCY_PAIR,POSITION_SOURCE_ID,CUST_CONTRACT_AMOUNT, COMMISSION FROM JHF_SYS_POSITION_INSERT WHERE POSITION_SOURCE_ID IN (
    SELECT EXECUTION_ID FROM JHF_ALIVE_EXECUTION WHERE ORDER_ID IN (
    SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009110400288606'
)
);

SELECT CASHFLOW_ID,CASHFLOW_SOURCE_ID, CASHFLOW_TYPE,SETTLEMENT_COMMISSION_TYPE,CUSTOMER_ID, CASHFLOW_AMOUNT_ORIGINAL,CASHFLOW_AMOUNT 
FROM JHF_UNREALIZED_CASHFLOW WHERE CASHFLOW_SOURCE_ID IN (
    SELECT EXECUTION_ID FROM JHF_ALIVE_EXECUTION WHERE ORDER_ID IN (
    SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009110400288606')
);


//*********************************************

SELECT * FROM JHF_COMMISSION_CONFIG WHERE CURRENCY_PAIR = 'USD/JPY' AND GROUP_ID = 'DEFAULT';

UPDATE JHF_COMMISSION_CONFIG SET LOT_P3_COMMISSION = '30' WHERE CURRENCY_PAIR  = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 0;
UPDATE JHF_COMMISSION_CONFIG SET LOT_P3_COMMISSION = '40' WHERE CURRENCY_PAIR  = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 1;
UPDATE JHF_COMMISSION_CONFIG SET LOT_P3_COMMISSION = '40' WHERE CURRENCY_PAIR  = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 2;
UPDATE JHF_COMMISSION_CONFIG SET AVAILABLE_FLAG = 1 WHERE CURRENCY_PAIR  = 'USD/JPY' AND GROUP_ID = 'DEFAULT';






SELECT * FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' ;

SELECT NEXT_EOD_START_TIME FROM JHF_APPLICATION_DATE ;

UPDATE JHF_APPLICATION_DATE SET NEXT_EOD_START_TIME = DATE_ADD(CURRENT_TIMESTAMP, interval 3 day) WHERE DATE_KEY IN ('F','S');




;


SELECT * FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR IN( 'USD/JPY' ,'EUR/JPY') ;

UPDATE  JHF_CUSTTRADE_CONTRL SET TRADE_LOWER_AMOUNT = 0  WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;

-- SELECT   JHF_COMMISSION_CONFIG  , JHF_COMMISSION_SPECIAL_CONFIG
SELECT *  FROM JHF_COMMISSION_CONFIG         WHERE  CURRENCY_PAIR = 'USD/JPY' AND GROUP_ID = 'DEFAULT' ;

SELECT *  FROM JHF_COMMISSION_SPECIAL_CONFIG WHERE  CURRENCY_PAIR = 'USD/JPY' AND GROUP_ID = 'DEFAULT' ;

SELECT *  FROM JHF_COMMISSION_SPECIAL_CONFIG_HISTORY WHERE  CURRENCY_PAIR = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' ORDER BY UPDATE_DATE DESC LIMIT 10;

-- UPDATE   JHF_COMMISSION_SPECIAL_CONFIG

UPDATE JHF_COMMISSION_SPECIAL_CONFIG SET LOT_P3_COMMISSION = 35 WHERE GROUP_ID = 'DEFAULT' AND CURRENCY_PAIR = 'EUR/JPY' AND TRADE_TYPE = '0'

-- UPDATE   JHF_COMMISSION_SPECIAL_CONFIG

UPDATE JHF_COMMISSION_CONFIG SET LOT_P3_COMMISSION = 35 WHERE GROUP_ID = 'DEFAULT' AND CURRENCY_PAIR = 'USD/JPY' AND TRADE_TYPE = '0'


/**
INSERT INTO JHF_COMMISSION_SPECIAL_CONFIG 
SELECT GROUP_ID,CURRENCY_PAIR,TRADE_TYPE,1,
LOT_P1_COMMISSION,
LOT_P2_COMMISSION,
LOT_P3_COMMISSION,
LOT_P4_COMMISSION,
LOT_P5_COMMISSION,
LOT_P6_COMMISSION,
LOT_P7_COMMISSION,
LOT_P8_COMMISSION,
LOT_P9_COMMISSION,
UPDATE_STAFF_ID,
INPUT_STAFF_ID,
ACTIVE_FLAG,
INPUT_DATE,
UPDATE_DATE

FROM JHF_NEXT_COMMISSION_SPECIAL_CONFIG WHERE  CURRENCY_PAIR = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' ;
**/

INSERT INTO JHF_COMMISSION_SPECIAL_CONFIG SELECT GROUP_ID,CURRENCY_PAIR,TRADE_TYPE,

LOT_P1_COMMISSION,
LOT_P2_COMMISSION,
LOT_P3_COMMISSION,
LOT_P4_COMMISSION,
LOT_P5_COMMISSION,
LOT_P6_COMMISSION,
LOT_P7_COMMISSION,
LOT_P8_COMMISSION,
LOT_P9_COMMISSION,
UPDATE_STAFF_ID,
INPUT_STAFF_ID,
ACTIVE_FLAG,
INPUT_DATE,
UPDATE_DATE  FROM JHF_NEXT_COMMISSION_SPECIAL_CONFIG WHERE  CURRENCY_PAIR = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' ;

SELECT *  FROM JHF_NEXT_COMMISSION_SPECIAL_CONFIG WHERE  CURRENCY_PAIR = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' ;



SELECT *  FROM JHF_COMMISSION_SPECIAL_CONFIG WHERE  CURRENCY_PAIR = 'EUR/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 1
;
UPDATE JHF_COMMISSION_CONFIG   
SET LOT_P1_COMMISSION = '0',
 LOT_P2_COMMISSION = '0', 
 LOT_P3_COMMISSION = '0', 
 LOT_P4_COMMISSION = '0', 
 LOT_P5_COMMISSION = '0', 
 LOT_P6_COMMISSION = '500', 
 LOT_P7_COMMISSION = '0', 
 LOT_P8_COMMISSION = '0', 
 LOT_P9_COMMISSION = '0' 
 
WHERE CURRENCY_PAIR  = 'USD/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 2;


UPDATE JHF_COMMISSION_SPECIAL_CONFIG   
SET LOT_P1_COMMISSION = '100',
 LOT_P2_COMMISSION = '200', 
 LOT_P3_COMMISSION = '300', 
 LOT_P4_COMMISSION = '400', 
 LOT_P5_COMMISSION = '500', 
 LOT_P6_COMMISSION = '600', 
 LOT_P7_COMMISSION = '700', 
 LOT_P8_COMMISSION = '800', 
 LOT_P9_COMMISSION = '900' 
 
WHERE CURRENCY_PAIR  = 'USD/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 2;




SELECT LOT_P6_COMMISSION  FROM JHF_COMMISSION_CONFIG WHERE  CURRENCY_PAIR = 'USD/JPY' AND GROUP_ID = 'DEFAULT' AND TRADE_TYPE = 1







---  LOSS 
;


SELECT PRODUCT_ID,LEVERAGE_LEVEL_ID,CURRENCY_PAIR,LOSSCUT_COMMISSION FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'EUR/JPY'
SELECT PRODUCT_ID,LEVERAGE_LEVEL_ID,CURRENCY_PAIR,LOSSCUT_COMMISSION FROM JHF_PRODUCT WHERE PRODUCT_ID = 'B002'


SELECT * FROM JHF_PRODUCT WHERE PRODUCT_ID = 'A001' ORDER BY INPUT_DATE DESC;


UPDATE JHF_PRODUCT  SET LOSSCUT_COMMISSION = LEVERAGE_LEVEL_ID WHERE PRODUCT_ID='C002';

SELECT * FROM JHF_APPLICATION_DATE;





SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%TstORD%' AND ORDER_STATUS = 3 ;

SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%TstORD%' AND ORDER_STATUS =7 ;

SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%TstORD%' AND ORDER_STATUS <> 3 ;

SELECT * FROM JHF_ALIVE_ORDER WHERE ORDER_ID = 'TstORD0' ;

SELECT ORDER_ID,ORDER_BIND_ID FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%TstORD%' AND ORDER_STATUS =7 limit 5;

SELECT UPDATE_DATE FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%TstORD%' AND ORDER_STATUS = 3 ORDER BY UPDATE_DATE ASC LIMIT 3;


SELECT UPDATE_DATE FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%TstORD%' AND ORDER_STATUS = 3 ORDER BY UPDATE_DATE DESC LIMIT 3;



show create table JHF_COMMISSION_SPECIAL_CONFIG;

show create table JHF_NEXT_COMMISSION_SPECIAL_CONFIG;


SELECT ORDER_ID,EXECUTION_MODE FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%TstORD299%' AND ORDER_STATUS = 3 ORDER BY ORDER_ID DESC;








SELECT * FROM JHF_CONTRACT_STATUS_HISTORY WHERE CONTRACT_ID = '20091021CONT00046918'
SELECT SETTLEMENT_COMMISSION  FROM JHF_ALIVE_CONTRACT_BK WHERE CONTRACT_ID = '20091021CONT00046918'
;
SELECT * JHF_COMMISS 
SELECT * FROM JHF_APPLICATION_DATE




SELECT ORDER_ID,SIDE,ORDER_AMOUNT,ORDER_STATUS,EXECUTION_PRICE,EXECUTION_MODE FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009102302318001'

SELECT ORDER_BIND_ID,ORDER_ID,CUSTOMER_ORDER_NO, CUSTOMER_ID ,INPUT_DATE,UPDATE_DATE,ORDER_TYPE ,EXECUTION_TYPE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000120' ORDER BY INPUT_DATE DESC;


