


SELECT * FROM JHF_APPLICATION_DATE


SELECT * FROM JHF_TRADE_CONSTRAINT;


UPDATE JHF_TRADE_CONSTRAINT 
SET MARKET_CLOSE_FLAG = 0 ,
OPEN_BUY_CONSTRAINT = 0 ,
OPEN_SELL_CONSTRAINT = 0 ,
CLOSE_BUY_CONSTRAINT = 0 ,
CLOSE_SELL_CONSTRAINT = 0 ,
DL_BUY_CONSTRAINT = 0 ,
SWAPGET_CONSTRAINT = 0 ,
DL_SELL_CONSTRAINT = 0 ,
MCUT_COMPUTE_CONSTRAINT = 0 ;





SELECT * FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'EUR/JPY';

UPDATE JHF_CUSTTRADE_CONTRL SET TRADE_UPPER_AMOUNT = 200000 WHERE CURRENCY_PAIR = 'EUR/JPY' AND CUSTTRADE_BAND = 2  ;

UPDATE JHF_CUSTTRADE_CONTRL SET TRADE_LOWER_AMOUNT = 210000 WHERE CURRENCY_PAIR = 'EUR/JPY' AND CUSTTRADE_BAND = 3  ;


