


SELECT * FROM JHF_CUSTOMER_SPECIAL WHERE CUSTOMER_ID = '00000101';





SELECT CURRENCY_PAIR,CUSTTRADE_BAND, AUTOHEDGE_SWATICH,INSTANT_OPEN_PRICE_SWATICH,INSTANT_CLOSE_PRICE_SWATICH  
FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY';


SELECT * 
FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY';


UPDATE JHF_CUSTTRADE_CONTRL SET INSTANT_OPEN_PRICE_SWATICH = -1 WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ; 


UPDATE JHF_CUSTTRADE_CONTRL SET INSTANT_OPEN_PRICE_SWATICH = 4,INSTANT_OPEN_SLIP_CONFIG_TYPE = 3 WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ; 

SELECT * FROM JHF_CUSTOMER_SPECIAL WHERE CUSTOMER_ID = '00000101' AND CURRENCY_PAIR = 'USD/JPY';

UPDATE JHF_CUSTOMER_SPECIAL SET SPECIAL_SWATICH = 1 WHERE CUSTOMER_ID = '00000101' AND CURRENCY_PAIR = 'USD/JPY';