SELECT * FROM JHF_CP_AUTOBAHN_EXECUTION where COUNTERPARTY_ID = 'GKGOH';

SELECT *
SELECT * FROM JHF_CP_DAILY_RATE_SUMMARY WHERE COUNTERPARTY_ID = 'GKGOH' 

UPDATE JHF_CP_DAILY_RATE_SUMMARY  SET RATE_DATE = '20101110' WHERE COUNTERPARTY_ID = 'GKGOH'

SHOW CREATE TABLE JHF_CP_DAILY_RATE_SUMMARY

INSERT INTO JHF_CP_DAILY_RATE_SUMMARY ( COUNTERPARTY_ID,CURRENCY_PAIR ,
RATE_DATE,
OPEN_ASK,
OPEN_BID,
OPEN_PRICE_TIME,OPEN_MID,
HIGH_ASK,
HIGH_BID,
HIGH_PRICE_TIME,
HIGH_MID,
LOW_ASK,
LOW_BID,
LOW_PRICE_TIME,
LOW_MID,
CLOSE_ASK,
CLOSE_BID,
CLOSE_PRICE_TIME,
CLOSE_MID,
ACTIVE_FLAG,
INPUT_DATE,
UPDATE_DATE,
IS_ESTIMATE_CP ) 
SELECT 'GKGOH',CURRENCY_PAIR ,
'20101109',
OPEN_ASK,
OPEN_BID,
OPEN_PRICE_TIME,OPEN_MID,
HIGH_ASK,
HIGH_BID,
HIGH_PRICE_TIME,
HIGH_MID,
LOW_ASK,
LOW_BID,
LOW_PRICE_TIME,
LOW_MID,
CLOSE_ASK,
CLOSE_BID,
CLOSE_PRICE_TIME,
CLOSE_MID,
ACTIVE_FLAG,
INPUT_DATE,
UPDATE_DATE,
IS_ESTIMATE_CP 
FROM JHF_CP_DAILY_RATE_SUMMARY WHERE COUNTERPARTY_ID = 'DB' GROUP BY CURRENCY_PAIR 