


-- close market    


SELECT * FROM JHF_TRADE_CONSTRAINT 

-- open
UPDATE JHF_TRADE_CONSTRAINT SET MARKET_CLOSE_FLAG = 0 ;
-- close
UPDATE JHF_TRADE_CONSTRAINT SET MARKET_CLOSE_FLAG = 1 ;


SELECT CURRENCY_PAIR,CROSS_RATE_SWITCH,CROSS_CURRENCY_PAIR1 ,CROSS_CURRENCY_PAIR2 FROM JHF_STATUS_CONTRL WHERE CROSS_RATE_SWITCH = 1 ;


SELECT CURRENCY_PAIR,CROSS_RATE_SWITCH,CROSS_CURRENCY_PAIR1 ,CROSS_CURRENCY_PAIR2 
FROM JHF_STATUS_CONTRL WHERE CROSS_CURRENCY_PAIR1 IS NOT NULL ;



