






/** 

JHF_CUSTOMER
JHF_PERSONAL
JHF_MAIL_ADDRESS
JHF_CUST_BANK_ACCOUNT
JHF_CUSTOMER_STATUS
JHF_CASH_BALANCE
JHF_CUSTOMER_LOCK
JHF_ORDER_NO_GENERATOR

**/




SELECT * FROM JHF_CUSTOMER WHERE CUSTOMER_ID = '00064401';
SELECT * FROM JHF_CUSTOMER ORDER BY CUSTOMER_ID DESC;
DELETE FROM JHF_CUSTOMER WHERE CUSTOMER_ID > '00064000';

SELECT * FROM JHF_PERSONAL WHERE CUSTOMER_ID = '00064401';
SELECT COUNT(*) FROM JHF_PERSONAL

SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '00000101';
SELECT * FROM JHF_PERSONAL WHERE CUSTOMER_ID = '00064101';
DELETE FROM JHF_PERSONAL WHERE CUSTOMER_ID > '00064000';

SELECT * FROM JHF_BANK_BRANCH;
SELECT * FROM JHF_CUST_BANK_ACCOUNT;
DELETE FROM JHF_CUST_BANK_ACCOUNT WHERE CUSTOMER_ID > '00064000';

SELECT * FROM JHF_MAIL_ADDRESS WHERE CUSTOMER_ID = '00000101';


SELECT * FROM JHF_CASH_BALANCE WHERE CUSTOMER_ID = '00000101';
SELECT * FROM JHF_CUSTOMER_LOCK WHERE CUSTOMER_ID = '00000101';
SELECT * FROM JHF_CUST_BANK_ACCOUNT WHERE CUSTOMER_ID = '00000101';
SELECT * FROM JHF_ORDER_NO_GENERATOR WHERE CUSTOMER_ID = '00000101';


SELECT * FROM UNIQUE_ID_GENERATOR WHERE CONTEXT_ID = 'CUST';
UPDATE UNIQUE_ID_GENERATOR SET CURRENT_COUNT = 66000 WHERE CONTEXT_ID = 'CUST';

SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '00003242' ;
UPDATE JHF_CUSTOMER_STATUS SET LOGIN_ID = 'I3900001',LOGIN_PASSWORD = 'bc177a7a9c7df69c248647b4dfc6fd84' WHERE CUSTOMER_ID = '00000101' ;

SELECT * FROM JHF_CUSTOMER WHERE CUSTOMER_ID = '00064001';

SELECT  los FROM JHF_CUSTOMER_STATUS  WHERE CUSTOMER_ID > '00064001' and CUSTOMER_ID < '00070000' order by CUSTOMER_ID desc;
;


SELECT * FROM JHF_MAIL_ACTION WHERE ;
SELECT * FROM JHF_MAIL_ADDRESS WHERE CUSTOMER_ID = '00065201';
SELECT * FROM JHF_MAIL_ACTION_MAP WHERE CUSTOMER_ID = '00065201';


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'JHF_GROUP'
SELECT * FROM JHF_GROUP_PRODUCT_BAND WHERE GROUP_ID = 'DEFAULT' AND ACTIVE_FLAG = 1


SHOW CREATE TABLE JHF_PERSONAL;
SHOW CREATE TABLE JHF_CUSTOMER_STATUS;


SELECT * FROM JHF_ORDER_NO_GENERATOR WHERE CUSTOMER_ID = '00066401'

INSERT INTO JHF_ORDER_NO_GENERATOR(CUSTOMER_ID, CUSTOMER_ORDER_NO, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE) 
    VALUES('00066401', 100, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;


