
SELECT * FROM JHF_APPLICATION_DATE

--- CUSTOMER  ????


UPDATE JHF_CUSTOMER_STATUS SET LOGIN_PASSWORD = '593c9b4a9390551d53e5cacf28ebd638' WHERE CUSTOMER_ID = '00000014';

SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '00000239';
UPDATE JHF_CUSTOMER_STATUS SET ACCOUNT_ACTIVE_STATUS = 0 WHERE CUSTOMER_ID = '00000014';
UPDATE JHF_CUSTOMER_STATUS SET OPEN_BUY_CONSTRAINT = 0 ,OPEN_SELL_CONSTRAINT=0,CLOSE_BUY_CONSTRAINT=0 ,CLOSE_SELL_CONSTRAINT=0 ,WITHDRAWAL_CONSTRAINT=0 ,LOSSCUT_CONSTRANT=0 
WHERE CUSTOMER_ID = '00000014';


SELECT ACCOUNT_OPEN_STATUS FROM JHF_CUSTOMER WHERE CUSTOMER_ID = '00093437';
UPDATE JHF_CUSTOMER SET ACCOUNT_OPEN_STATUS = 8 WHERE CUSTOMER_ID = '00000014';


select * from JHF_CUSTOMER_STATUS where CUSTOMER_ID = '00000014'



CREATE TABLE JHF_CUSTOMER_STATUS ( 
	CUSTOMER_ID                 	VARCHAR(40) NOT NULL,
	GROUP_ID                    	VARCHAR(40) NOT NULL,
	WITHDRAWAL_CONSTRAINT       	DECIMAL(1,0) NULL,
	ACCOUNT_STATUS              	DECIMAL(2,0) NULL,
	RISK_ACCOUNT_STATUS         	DECIMAL(2,0) NULL,
	LOGIN_CONSTRAINT            	DECIMAL(1,0) NULL,
	OPEN_BUY_CONSTRAINT         	DECIMAL(1,0) NULL,
	OPEN_SELL_CONSTRAINT        	DECIMAL(1,0) NULL,
	CLOSE_BUY_CONSTRAINT        	DECIMAL(1,0) NULL,
	CLOSE_SELL_CONSTRAINT       	DECIMAL(1,0) NULL,
	STRADDLE_OPTION_FLAG        	DECIMAL(1,0) NULL,
	ACCOUNT_ACTIVE_STATUS       	DECIMAL(1,0) NULL,
	ACCOUNT_ACTIVE_STATUS_DATE  	VARCHAR(16) NULL,
	LOGIN_ID                    	VARCHAR(256) NULL,
	LOGIN_PASSWORD              	VARCHAR(256) NULL,
	OLD_LOGIN_PASSWORD          	VARCHAR(256) NULL,
	ORIGINAL__PASSWORD          	VARCHAR(256) NULL,
	PASSWORD_UPDATE_DATE        	VARCHAR(16) NULL,
	UPPER_AMOUNT                	DECIMAL(15,2) NULL,
	FUTURE_GROUP_ID             	VARCHAR(40) NULL,
	FUTURE_GROUP_CHANGE_DATE    	VARCHAR(16) NULL,
	NOTICE_RATIO                	DECIMAL(8,4) NULL,
	WITHDRAWAL_COUNT            	DECIMAL(2,0) NULL,
	TOTAL_CREDIT                	DECIMAL(15,2) NULL,
	LAST_LOGIN_TIME             	TIMESTAMP NULL,
	PASSWORD_FAIL_COUNT         	DECIMAL(2,0) NULL,
	CLOSE_REQUEST_FLAG          	DECIMAL(1,0) NULL,
	COMMISSION_FREE_FLAG        	DECIMAL(1,0) NULL,
	DELIVERY_RECIEPT_CONSTRAINT 	DECIMAL(1,0) NULL,
	DELIVERY_DELIVERY_CONSTRAINT	DECIMAL(1,0) NULL,
	CONVERSION_IN_CONSTRAINT    	DECIMAL(1,0) NULL,
	CONVERSION_OUT_CONSTRAINT   	DECIMAL(1,0) NULL,
	AFFINITY_KEY                	VARCHAR(16) NULL,
	SERVICE_POINT               	DECIMAL(3,0) NULL,
	UPDATE_STAFF_ID             	VARCHAR(12) NULL,
	INPUT_STAFF_ID              	VARCHAR(12) NULL,
	ACTIVE_FLAG                 	DECIMAL(1,0) NULL,
	INPUT_DATE                  	TIMESTAMP NOT NULL,
	UPDATE_DATE                 	TIMESTAMP NOT NULL,
	VIRTUAL_ACCOUNT_NO          	VARCHAR(40) NULL,
	LOSSCUT_MAIL_COUNT          	DECIMAL(2,0) NULL,
	RISK_CONTROL_STATUS         	DECIMAL(1,0) NULL,
	RISK_CONTROL_PROFIT_FLAG    	DECIMAL(1,0) NULL,
	RISK_CONTROL_PROFIT_VALUE   	DECIMAL(15,0) NULL,
	RISK_CONTROL_LOSS_FLAG      	DECIMAL(1,0) NULL,
	RISK_CONTROL_LOSS_VALUE     	DECIMAL(15,0) NULL,
	RISK_CONTROL_ACTIVE_FLAG    	DECIMAL(1,0) NULL,
	ALERT_MAIL_COUNT            	DECIMAL(2,0) NULL,
	LOSSCUT_RATIO               	DECIMAL(8,4) NULL,
	ALERT_RATIO                 	DECIMAL(8,4) NULL,
	LOSSCUT_RATIO_FLAG          	DECIMAL(1,0) NULL,
	ALERT_RATIO_FLAG            	DECIMAL(1,0) NULL,
	LOSSCUT_CONSTRANT           	DECIMAL(1,0) NOT NULL 
	);
INSERT INTO JHF_CUSTOMER_STATUS(CUSTOMER_ID, GROUP_ID, WITHDRAWAL_CONSTRAINT, ACCOUNT_STATUS, RISK_ACCOUNT_STATUS, LOGIN_CONSTRAINT, OPEN_BUY_CONSTRAINT, OPEN_SELL_CONSTRAINT, CLOSE_BUY_CONSTRAINT, CLOSE_SELL_CONSTRAINT, STRADDLE_OPTION_FLAG, ACCOUNT_ACTIVE_STATUS, ACCOUNT_ACTIVE_STATUS_DATE, LOGIN_ID, LOGIN_PASSWORD, OLD_LOGIN_PASSWORD, ORIGINAL__PASSWORD, PASSWORD_UPDATE_DATE, UPPER_AMOUNT, FUTURE_GROUP_ID, FUTURE_GROUP_CHANGE_DATE, NOTICE_RATIO, WITHDRAWAL_COUNT, TOTAL_CREDIT, LAST_LOGIN_TIME, PASSWORD_FAIL_COUNT, CLOSE_REQUEST_FLAG, COMMISSION_FREE_FLAG, DELIVERY_RECIEPT_CONSTRAINT, DELIVERY_DELIVERY_CONSTRAINT, CONVERSION_IN_CONSTRAINT, CONVERSION_OUT_CONSTRAINT, AFFINITY_KEY, SERVICE_POINT, UPDATE_STAFF_ID, INPUT_STAFF_ID, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE, VIRTUAL_ACCOUNT_NO, LOSSCUT_MAIL_COUNT, RISK_CONTROL_STATUS, RISK_CONTROL_PROFIT_FLAG, RISK_CONTROL_PROFIT_VALUE, RISK_CONTROL_LOSS_FLAG, RISK_CONTROL_LOSS_VALUE, RISK_CONTROL_ACTIVE_FLAG, ALERT_MAIL_COUNT, LOSSCUT_RATIO, ALERT_RATIO, LOSSCUT_RATIO_FLAG, ALERT_RATIO_FLAG, LOSSCUT_CONSTRANT)
  VALUES('90000088', 'DEFAULT', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '20080716', 'EMFX0088', 'bc177a7a9c7df69c248647b4dfc6fd84', 'aEpaN1pucGo=', 'aEpaN1pucGo=', '20080716', 0.00, '', '', 0.0000, 0, 0.00, '2008-12-20 14:27:17.0', 0, 0, 0, 0, 0, 0, 0, '', 0, 'CS0001', 'CS0001', 1, '2008-12-20 14:27:17.0', '2009-02-06 14:58:11.0', '', 0, 0, 0, 0, 0, 0, 0, 0, 0.0000, 0.0000, 0, 0, 0);



--================

    --   SAM  DB

--================

SELECT * FROM JHF_CUSTOMER WHERE CUSTOMER_ID='00000007' AND 

SELECT * FROM CUSTOMER  WHERE CUSTOMER_ID='00000007' 

insert into JHF_ORDER_NO_GENERATOR values ('70058888',1000,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
