CALL PANTA_DELETE_CUSTOMERS(90010000, 90010300);


DELETE FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID LIKE '9%' ;
DELETE FROM JHF_CUSTOMER_CONFIG WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_CUSTOMER WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_CUST_BANK_ACCOUNT WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_MAIL_ADDRESS WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_PERSONAL WHERE CUSTOMER_ID LIKE '9%' ;
DELETE FROM JHF_CASH_BALANCE WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_CUSTOMER_LOCK WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_MAIL_ACTION_MAP WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_LEVERAGE_GROUP WHERE CUSTOMER_ID LIKE '9%'  ;
DELETE FROM JHF_ORDER_NO_GENERATOR WHERE CUSTOMER_ID LIKE '9%'  ;