

SELECT ORDER_ID,CURRENCY_PAIR,SIDE, CUSTOMER_ID,EXECUTION_TYPE ,ORDER_AMOUNT,PRICE_ID,ORDER_PRICE, EXECUTION_PRICE, TRADERTIME_PRICE_ID,TRADERTIME_PRICE,CP_PRICE_ID,CP_PRICE,EXECUTION_MODE ,INPUT_DATE,UPDATE_DATE 
FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID = '2009083101776504' ;


SELECT ORDER_ID,ORDER_BIND_ID,ORDER_STATUS ,CURRENCY_PAIR,SIDE, CUSTOMER_ID,EXECUTION_TYPE ,ORDER_AMOUNT,PRICE_ID,ORDER_PRICE, EXECUTION_PRICE, TRADERTIME_PRICE_ID,TRADERTIME_PRICE,CP_PRICE_ID,CP_PRICE,EXECUTION_MODE ,INPUT_DATE,UPDATE_DATE 
FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000014' ORDER BY INPUT_DATE DESC LIMIT 10;


SELECT ORDER_BIND_ID FROM JHF_ALIVE_ORDER WHERE ORDER_ID = '20090827ORD00502534'

SELECT ORDER_ID,PRICE_ID, TRADERTIME_PRICE_ID,TRADERTIME_PRICE,CP_PRICE_ID,CP_PRICE,EXECUTION_MODE ,REVISION_NUMBER,ORDER_STATUS FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID = '20090826ORD00494002';







SELECT TRADE_PRICE,EXECUTION_PRICE FROM JHF_ALIVE_ORDER WHERE ORDER_ID = '20090827ORD00502535'

SELECT ORDER_ID,CURRENCY_PAIR,SIDE, CUSTOMER_ID,EXECUTION_TYPE ,ORDER_AMOUNT,PRICE_ID,ORDER_PRICE, EXECUTION_PRICE, TRADERTIME_PRICE_ID,TRADERTIME_PRICE,CP_PRICE_ID,CP_PRICE,EXECUTION_MODE ,INPUT_DATE,UPDATE_DATE  FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID = '20090831ORD00526749' ;

SELECT * FROM JHF_APPLICATION_DATE

SELECT * FROM JHF_SPOT_RATE_CONFIG WHERE CURRENCY_PAIR = 'EUR/JPY'