

/**
??????????????????????+??????+?????


??????????????????????swap??????T+1????

?????????????????????swap??????T+2?????
? ??????????????????????
*/




















SELECT * FROM JHF_APPLICATION_DATE
SELECT * FROM JHF_SYSTEM_CONFIGURATION

SELECT * FROM JHF_SYSTEM_CONFIGURATION_HISTORY WHERE FUNC_ID = 'FormulaDiffService'



SELECT * FROM JHF_SYSTEM_CONFIGURATION;


SELECT  LOSSCUT_RATIO  , ALERT_RATIO ,NOTICE_RATIO  FROM JHF_GROUP

--  FORMULA  DIFF  Êý¾Ý
-- FORMULA SERVICE 
INSERT INTO JHF_SYSTEM_CONFIGURATION(FUNC_MODULE, FUNC_ID, FUNC_VALUE, FUNC_COMMENT, FUNC_GROUP, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE) 
    VALUES('Formula', 'FormulaDiffService', 'cn.bestwiz.jhf.core.formula.diff.service.FormulaDiffService4Panta', 'Formula Diff', 'Middle', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;
-- FORMULA BUSINESS
INSERT INTO JHF_SYSTEM_CONFIGURATION(FUNC_MODULE, FUNC_ID, FUNC_VALUE, FUNC_COMMENT, FUNC_GROUP, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE) 
    VALUES('Formula', 'FormulaDiffBusiness', 'cn.bestwiz.jhf.core.formula.diff.business.FormulaDiffBusiness4Panta', 'Formula Diff', 'Middle', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;



--  LOSSCUT  DIFF  Êý¾Ý
INSERT INTO JHF_SYSTEM_CONFIGURATION(FUNC_MODULE, FUNC_ID, FUNC_VALUE, FUNC_COMMENT, FUNC_GROUP, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE) 
    VALUES('Losscut', 'LosscutProcessor', 'cn.bestwiz.jhf.trader.losscut.diff.processor.LosscutProcessor4Panta', 'Losscut Diff', 'Middle', 1, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
;


--  LOSS CUT DEFAULT   
INSERT INTO JHF_SYSTEM_CONFIGURATION(FUNC_MODULE, FUNC_ID, FUNC_VALUE, FUNC_COMMENT, FUNC_GROUP, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE) 
    VALUES('Losscut', 'LosscutProcessor', 'cn.bestwiz.jhf.trader.losscut.processor.DefaultLosscutProcessor', 'Losscut Diff', 'Middle', 1, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
;




-- É¾³ý 
DELETE FROM JHF_SYSTEM_CONFIGURATION WHERE FUNC_MODULE = 'Formula' AND FUNC_ID = 'LosscutProcessor' ;






SELECT * FROM JHF_SYSTEM_CONFIGURATION WHERE FUNC_MODULE = 'Losscut' AND FUNC_ID = 'LosscutProcessor'

SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID ='00000101' AND ORDER_STATUS=7;
DELETE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID ='00000142' AND ORDER_STATUS=7;
DELETE FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID ='00000142'

--  ¸üÐÂ  LOSSCT NOTIC ALERT ÂÊ   ÔÚ JHF_GROUP ±í
UPDATE JHF_GROUP SET LOSSCUT_RATIO = 1.00 , ALERT_RATIO = 1.30 ,NOTICE_RATIO = 1.50 


SELECT SUM(CASHFLOW_AMOUNT)  FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00000101' AND CASHFLOW_TYPE IN (3,4,5,6,9,12);









SELEC

SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'EUR/USD';

UPDATE JHF_PRODUCT SET MIN_QUANTITY = 1000 WHERE CURRENCY_PAIR = 'EUR/USD' AND LEVERAGE_LEVEL_ID = 100;

SELECT GROUP_ID, LOSSCUT_RATIO,ALERT_RATIO,NOTICE_RATIO FROM JHF_CUSTOMER_STATUS 




SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE='RATE'

hedgerate4slipexpiredtime



INSERT INTO JHF_APP_PROPERTY(PROP_TYPE, PROPERTY_KEY, PROPERTY_VALUE, DISPLAY_NAME, NOTE, UPDATE_STAFF_ID, INPUT_STAFF_ID, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE) 
    VALUES('RATE', 'hedgerate4slipexpiredtime', '20000', '', 'hedgRate expire time', 'system', 'system', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;





SELECT NOTICE_RATIO ,ALERT_RATIO,LOSSCUT_WARN_RATIO, LOSSCUT_RATIO FROM JHF_GROUP WHERE GROUP_ID  ='DEFAULT'


SELECT PRODUCT_ID,TRADE_DEPOSIT,LEVERAGE_LEVEL_ID FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'USD/JPY';
SELECT TRADE_DEPOSIT FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'USD/JPY' AND LEVERAGE_LEVEL_ID = 100 


-- ¼ÆËã³Ö²Ö±£Ö¤½ð×Ü¶î 
SELECT SUM(SP.V) FROM (
SELECT CNT.PRODUCT_ID,CNT.AMOUNT_NO_SETTLED ,PDT.LEVERAGE_LEVEL_ID, PDT.TRADE_DEPOSIT 
   ,( CNT.AMOUNT_NO_SETTLED * TRADE_DEPOSIT / PDT.LOT_SIZE) AS V  
FROM JHF_ALIVE_CONTRACT CNT

LEFT OUTER JOIN JHF_PRODUCT PDT ON PDT.PRODUCT_ID =CNT.PRODUCT_ID 

WHERE  CNT.CUSTOMER_ID = '00003242' AND CNT.AMOUNT_NO_SETTLED > 0 AND CNT.STATUS = 1 


) AS SP



-- ¼ÆËã×¢ÎÄ±£Ö¤½ð×Ü¶î 


SELECT SUM(SO.V) FROM (
SELECT OD.PRODUCT_ID,PDT.LEVERAGE_LEVEL_ID, PDT.TRADE_DEPOSIT ,OD.ORDER_AMOUNT ,OD.CURRENCY_PAIR 
   ,( OD.ORDER_AMOUNT * TRADE_DEPOSIT / PDT.LOT_SIZE) AS V  
FROM JHF_ALIVE_ORDER OD

LEFT OUTER JOIN JHF_PRODUCT PDT ON PDT.PRODUCT_ID =OD.PRODUCT_ID 

WHERE  OD.CUSTOMER_ID = '00003242' AND OD.ORDER_STATUS IN (0,1,7)  


) AS SO




-- ¼ÆËã½¨ÓñÆÀ¼ÛËðÒæ  £¨ #################>>>>> ½ö½öÓÃÓÚ JPY ½áÎ²µÄ»õ±Ò¶Ô £©
-- ÐèÒªÐÞ¸Ä  CUSTOMER_ID  £¬NOW_ASK £¬NOW_BID  £¬CURRENCY_PAIR

--ÙI½¨£º½¨Óñ½ðî~¡Á½¨‚Ž£¨¼s¶¨»ãÂÊ£©¡Á(-1)£«½¨Óñ½ðî~¡ÁÔu?ý»ãÂÊµÄBid
--‰Ó½¨£º½¨Óñ½ðî~¡Á½¨‚Ž£¨¼s¶¨»ãÂÊ£©£«½¨Óñ½ðî~¡ÁÔu?ý»ãÂÊµÄAsk¡Á(-1)

SELECT SUM(PVS.PV) FROM (
SELECT  CNT.SIDE,CNT.EXECUTION_PRICE,CNT.AMOUNT_NO_SETTLED ,

CASE WHEN SIDE = 1 
      THEN ( 1.31220 - CNT.EXECUTION_PRICE) * CNT.AMOUNT_NO_SETTLED 
      ELSE (  CNT.EXECUTION_PRICE - 1.31260) * CNT.AMOUNT_NO_SETTLED  END AS PV

FROM JHF_ALIVE_CONTRACT AS CNT 
WHERE CNT.CUSTOMER_ID = '00003242' AND CNT.AMOUNT_NO_SETTLED > 0 AND CNT.STATUS = 1 AND CURRENCY_PAIR = 'EUR/USD'
) AS PVS





-- ¼ÆËã½¨ÓñÆÀ¼ÛËðÒæ  £¨ #################>>>>> ½ö½öÓÃÓÚ ·ÇJPY ½áÎ²µÄ»õ±Ò¶Ô £©
-- ÐèÒªÐÞ¸Ä  CUSTOMER_ID  £¬NOW_ASK £¬NOW_BID  £¬CURRENCY_PAIR
SELECT SUM(PVS.PV) FROM (
SELECT  CNT.SIDE,CNT.EXECUTION_PRICE,CNT.AMOUNT_NO_SETTLED ,

CASE WHEN SIDE = 1 
      THEN ( 1.31220 - CNT.EXECUTION_PRICE) * CNT.AMOUNT_NO_SETTLED 
      ELSE (  CNT.EXECUTION_PRICE - 1.31260) * CNT.AMOUNT_NO_SETTLED  END AS PV

FROM JHF_ALIVE_CONTRACT AS CNT 
WHERE CNT.CUSTOMER_ID = '00003242' AND CNT.AMOUNT_NO_SETTLED > 0 AND CNT.STATUS = 1 AND CURRENCY_PAIR = 'EUR/USD'
) AS PVS






SELECT * FROM JHF_CUSTOMER_STATUS
SELECT * FROM JHF_GROUP_PRODUCT_BAND;


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE ='WITHDRAW';



---  ²éÑ¯ CASH BALANCE 

SELECT CASH_BALANCE FROM JHF_CASH_BALANCE WHERE CUSTOMER_ID = '00006701';


-- ³ö½ð¾ÐÊø½ð (³ö½ðÔ¤¶¨¶î)
SELECT WITHDRAWAL_AMOUNT FROM JHF_WITHDRAWAL WHERE CUSTOMER_ID = '00003242'

-- »ñµÃ contract µÄ swap ËðÒæ ×ÜºÍ  

SELECT SUM(SWAP_INTEREST) FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID = '00000101' AND AMOUNT_NO_SETTLED > 0 AND STATUS = 1 ;
SELECT * FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID = '00000101' AND AMOUNT_NO_SETTLED > 0 AND STATUS = 1 ;


UPDATE JHF_ALIVE_CONTRACT SET SWAP_INTEREST = 88 WHERE CONTRACT_ID = '20100105CONT00414227'

SELECT SUM(CASHFLOW_AMOUNT) FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00000101' 
 AND CASHFLOW_TYPE IN (3,4,5,6,9,10,12) 
 AND ACTIVE_FLAG = 1 ;


--- Èë³ö½ðÓè¶¨î~      ÏÖ½ðÁ÷ÀàÐÍÎªÈ¡Òý“pÒæ?9§9ÊÖÊýÁÏ?9§9swap¡¢¿±¶¨ÈÕÆÚÎªT+1µÄÏÖ½ðÁ÷

SELECT SUM(CASHFLOW_AMOUNT) FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00003242' 
 AND CASHFLOW_TYPE IN (3,4,5,6,9,10,12) 
 AND ACTIVE_FLAG = 1 AND VALUE_DATE = '20100119';

--- ¼È›Qœg“pÒæ       ÏÖ½ðÁ÷ÀàÐÍÎªÈ¡Òý“pÒæ?9§9ÊÖÊýÁÏ?9§9swap¡¢¿±¶¨ÈÕÆÚÎªT+2µÄÏÖ½ðÁ÷

SELECT SUM(CASHFLOW_AMOUNT) FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00003242' 
 AND CASHFLOW_TYPE IN (3,4,5,6,9,10,12) 
 AND ACTIVE_FLAG = 1 AND VALUE_DATE = '20100120';


SELECT VALUE_DATE FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00000101' 
 AND CASHFLOW_TYPE IN (3,4,5,6,9,10,12) 
 AND ACTIVE_FLAG = 1 ;


DELETE  FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00000101' AND VALUE_DATE = '20091210';

SELECT DAYOFWEEK('20100112');

SELECT * FROM JHF_HOLIDAY


SELECT * FROM JHF_APPLICATION_DATE
SELECT * FROM JHF_TRADE_CONSTRAINT
--- ===========================



SELECT * FROM JHF_MARGIN_ACCOUNT WHERE CUSTOMER_ID = '00003242';
UPDATE JHF_MARGIN_ACCOUNT SET ACCOUNT_STATUS =0 WHERE CUSTOMER_ID = '00003242';





SELECT * FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID = '00003242' AND AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING > 0 ;
DELETE FROM JHF_ALIVE_CONTRACT WHERE CONTRACT_ID = '20100113CONT00415471';



SELECT * FROM JHF_ALIVE_ORDER WHERE ORDER_STATUS = 1 AND CUSTOMER_ID = '00003242' AND ORDER_AMOUNT = '10000';
DELETE FROM JHF_ALIVE_ORDER WHERE ORDER_ID='20100113ORD00811501' AND ORDER_STATUS=7;


SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'USD/JPY'

SELECT * FROM JHF_APPLICATION_DATE
--- ³ö½ð¿ÉÄÜ¶î   ¹«Ê½±ä¸ü
SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00006701'
SELECT CASHFLOW_ID,CASHFLOW_AMOUNT,VALUE_DATE,CASHFLOW_TYPE FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00006701' AND VALUE_DATE > (SELECT FRONT_DATE FROM JHF_APPLICATION_DATE WHERE DATE_KEY='F') ;

UPDATE JHF_UNREALIZED_CASHFLOW SET CASHFLOW_AMOUNT = '-800000' WHERE CASHFLOW_ID = '20100309CASH01258965';
UPDATE JHF_UNREALIZED_CASHFLOW SET VALUE_DATE = '20100518' WHERE CASHFLOW_ID = '20100512CASH00027153';

SELECT CASHFLOW_ID,SUM(CASHFLOW_AMOUNT),VALUE_DATE,CASHFLOW_TYPE FROM JHF_UNREALIZED_CASHFLOW  
WHERE CUSTOMER_ID = '00006701' AND VALUE_DATE > (SELECT FRONT_DATE FROM JHF_APPLICATION_DATE WHERE DATE_KEY='F') GROUP BY VALUE_DATE;



SELECT CASHFLOW_ID,SUM(CASHFLOW_AMOUNT),VALUE_DATE,CASHFLOW_TYPE FROM JHF_UNREALIZED_CASHFLOW 
WHERE CUSTOMER_ID = '00001165' AND VALUE_DATE > '20100621' GROUP BY VALUE_DATE 
;

SELECT CONCAT('cidList.add("',CUSTOMER_ID,'");') FROM JHF_UNREALIZED_CASHFLOW 
WHERE  VALUE_DATE > '20100621' GROUP BY CUSTOMER_ID;


DELETE FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM JHF_UNREALIZED_CASHFLOW 
WHERE  VALUE_DATE > '20100101' GROUP BY CUSTOMER_ID);


SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000101' ORDER BY INPUT_DATE DESC;


SELECT CASHFLOW_ID,SUM(CASHFLOW_AMOUNT),VALUE_DATE,CASHFLOW_TYPE 
FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID IN ('00000101') AND VALUE_DATE > '20100604' GROUP BY VALUE_DATE ORDER BY CUSTOMER_ID, VALUE_DATE 

SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE VALUE_DATE = '20100607';
UPDATE JHF_UNREALIZED_CASHFLOW SET CASHFLOW_AMOUNT =CASHFLOW_AMOUNT - '0.56'    WHERE CASHFLOW_ID ='20100603CASH01262677'

SELECT * FROM JHF_APPLICATION_DATE


CREATE TABLE `JHF_ALIVE_CONTRACT` (
  `CONTRACT_ID` varchar(20) NOT NULL,
  `TRADE_TYPE` decimal(1,0) NOT NULL,
  `SETTLED_TYPE` decimal(1,0) DEFAULT '1',
  `SIDE` decimal(1,0) NOT NULL,
  `CONTRACT_CURRENCY_CODE` varchar(3) NOT NULL,
  `COUNTER_CURRENCY_CODE` varchar(3) NOT NULL,
  `PRODUCT_ID` varchar(4) NOT NULL,
  `TRADE_ID` varchar(20) NOT NULL,
  `ORDER_ID` varchar(40) NOT NULL,
  `REVISION_NUMBER` decimal(5,0) NOT NULL,
  `CURRENCY_PAIR` varchar(7) NOT NULL,
  `CP_PRICE` decimal(10,6) DEFAULT NULL,
  `CUSTOMER_ID` varchar(20) NOT NULL,
  `SWAP_INTEREST` decimal(15,2) NOT NULL,
  `SETTLEMENT_COMMISSION` decimal(15,2) DEFAULT NULL,
  `PREVIOUS_SWAP_INTEREST` decimal(15,2) DEFAULT NULL,
  `PRE_PREVIOUS_SWAP_INTEREST` decimal(15,2) DEFAULT NULL,
  `ORIGINAL_SETTLE_DATE` varchar(8) NOT NULL,
  `SETTLE_DATE` varchar(8) NOT NULL,
  `AMOUNT_NO_SETTLED` decimal(15,2) NOT NULL,
  `CURRENT_UNREALIZED_PL` decimal(15,2) DEFAULT NULL,
  `PREVIOUS_UNREALIZED_PL` decimal(15,2) DEFAULT NULL,
  `EXECUTION_DATETIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ORDER_PRICE` decimal(10,6) NOT NULL,
  `TRADE_PRICE` decimal(10,6) NOT NULL,
  `EXECUTION_PRICE` decimal(10,6) NOT NULL,
  `AMOUNT` decimal(15,2) NOT NULL,
  `ORDER_DATETIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `AMOUNT_SETTLED` decimal(15,2) NOT NULL,
  `OPEN_COMMISSION` decimal(15,2) NOT NULL,
  `AMOUNT_SETTLING` decimal(15,2) NOT NULL,
  `TODAY_ADDED_SWAP` decimal(15,2) DEFAULT NULL,
  `FORCE_RELATION_FLAG` decimal(1,0) DEFAULT NULL,
  `FORCE_RELATION_ID` varchar(20) DEFAULT NULL,
  `STATUS` decimal(1,0) DEFAULT NULL,
  `AGENT_STAFF_ID` varchar(6) DEFAULT NULL,
  `UPDATE_STAFF_ID` varchar(6) NOT NULL,
  `INPUT_STAFF_ID` varchar(6) NOT NULL,
  `ACTIVE_FLAG` decimal(1,0) DEFAULT NULL,
  `INPUT_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CUSTOMER_ORDER_NO` varchar(20) NOT NULL DEFAULT 'NULL',
  `CHANGE_REASON` decimal(2,0) NOT NULL,
  PRIMARY KEY (`CONTRACT_ID`),
  KEY `AliveContractIdx001` (`CUSTOMER_ID`,`AMOUNT_NO_SETTLED`,`ACTIVE_FLAG`,`STATUS`),
  KEY `ALIVE_CONTRACT_07` (`ORDER_ID`),
  KEY `ALIVE_CONTRACT_08` (`FORCE_RELATION_FLAG`),
  KEY `CUSTOMER_STATUS_02` (`CUSTOMER_ID`,`ACTIVE_FLAG`),
  KEY `Alive_CONtract_01` (`CUSTOMER_ID`,`AMOUNT_NO_SETTLED`,`STATUS`,`ACTIVE_FLAG`),
  KEY `Alive_CONtract_02` (`CUSTOMER_ID`,`CURRENCY_PAIR`,`AMOUNT_NO_SETTLED`,`STATUS`,`ACTIVE_FLAG`),
  KEY `Alive_CONtract_03` (`CUSTOMER_ID`,`AMOUNT_NO_SETTLED`,`STATUS`,`ACTIVE_FLAG`),
  KEY `ALIVE_CONTRACT_05` (`CUSTOMER_ID`,`SWAP_INTEREST`,`ACTIVE_FLAG`),
  KEY `ALIVE_ORDER_24` (`AMOUNT_NO_SETTLED`,`ACTIVE_FLAG`),
  KEY `ALIVE_CONTRACT_04` (`FORCE_RELATION_FLAG`,`AMOUNT_NO_SETTLED`)
) ENGINE=InnoDB DEFAULT CHARSET=cp932 


 Alter   TABLE JHF_CUSTOMER_STATUS RENAME TO JHF_CUSTOMER_STATUS_BAK ;
 Alter   TABLE JHF_WITHDRAWAL RENAME TO JHF_WITHDRAWAL_BAK ;


 Alter   TABLE JHF_CASH_BALANCE RENAME TO JHF_CASH_BALANCE_BAK ;

 Alter   TABLE JHF_UNREALIZED_CASHFLOW RENAME TO JHF_UNREALIZED_CASHFLOW_BAK ;
Alter   TABLE JHF_ALIVE_CONTRACT RENAME TO JHF_ALIVE_CONTRACT_BAK ;



DROP TABLE JHF_CUSTOMER_STATUS;
DROP TABLE JHF_WITHDRAWAL;
DROP TABLE JHF_CASH_BALANCE;
DROP TABLE JHF_UNREALIZED_CASHFLOW;
DROP TABLE JHF_ALIVE_CONTRACT;

SELECT * FROM JHF_WITHDRAWAL ORDER BY INPUT_DATE DESC LIMIT 10;

SELECT * FROM JHF_UNREALIZED_CASHFLOW ORDER BY INPUT_DATE DESC LIMIT 10;

show create table JHF_ALIVE_CONTRACT;

SELECT * FROM JHF_ALIVE_CONTRACT 




 Alter   TABLE JHF_CUSTOMER_STATUS_BAK RENAME TO JHF_CUSTOMER_STATUS ;
 Alter   TABLE JHF_WITHDRAWAL_BAK RENAME TO JHF_WITHDRAWAL  ;


 Alter   TABLE JHF_CASH_BALANCE_BAK RENAME TO JHF_CASH_BALANCE ;

 Alter   TABLE JHF_UNREALIZED_CASHFLOW_BAK RENAME TO JHF_UNREALIZED_CASHFLOW ;
Alter   TABLE JHF_ALIVE_CONTRACT_BAK RENAME TO JHF_ALIVE_CONTRACT ;

