SELECT * FROM JHF_APPLICATION_DATE

UPDATE JHF_APPLICATION_DATE SET FRONT_END_DATETIME = DATE_ADD(CURRENT_TIMESTAMP, interval 3 day) WHERE DATE_KEY IN ('F','S');
UPDATE JHF_APPLICATION_DATE SET NEXT_EOD_START_TIME = DATE_ADD(CURRENT_TIMESTAMP, interval 3 day) WHERE DATE_KEY IN ('F','S');


UPDATE JHF_APPLICATION_DATE SET FRONT_DATE = '20090828' WHERE DATE_KEY IN ('F','S');