

SELECT ORDER_ID,ORDER_PRICE,ORDER_AMOUNT FROM JHF_ALIVE_ORDER  WHERE CUSTOMER_ID='00060065' ORDER BY INPUT_DATE ASC LIMIT 10;


SELECT * FROM JHF_STATUS_CONTRL GROUP BY CURRENCY_PAIR;
;
SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'USD/JPY'  

SELECT * FROM JHF_APP_PROPERTY WHERE


SELECT ORDER_ID,ORDER_AMOUNT,UPDATE_DATE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00060065' ORDER BY INPUT_DATE DESC;


SELECT ORDER_ID,CUSTOMER_ID,ORDER_AMOUNT,UPDATE_DATE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID IN( '00060065','00060095','00060099') ORDER BY CUSTOMER_ID,INPUT_DATE DESC;

SELECT ORDER_ID,CUSTOMER_ID,ORDER_AMOUNT,UPDATE_DATE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00060099' ORDER BY CUSTOMER_ID,INPUT_DATE DESC;


SELECT * FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID = '20091109ORD00021514'

;
UPDATE JHF_CUSTOMER_STATUS SET LOGIN_PASSWORD = '593c9b4a9390551d53e5cacf28ebd638' WHERE CUSTOMER_ID = '00060099';




DELETE FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID IN( '00060065','00060095','00060099') AND AMOUNT_NO_SETTLED > 0 ;

DELETE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID IN('00060065','00060095','00060099')  ;


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'RATE' AND PROPERTY_KEY = 'ratecacheexpiredtime';
UPDATE JHF_APP_PROPERTY SET PROPERTY_VALUE = 99999999 WHERE PROP_TYPE = 'RATE' AND PROPERTY_KEY = 'ratecacheexpiredtime';


--========================================
INSERT INTO `JHF_PERSONAL` VALUES (@i,'0','001-1111-1111','13','Ü”òI','≤ø ','¬ö√˚','11','111-111-1111','111-111-1111','1','','0', '', 0, '', 0, 0, 0,1)

show create table JHF_PERSONAL;

INSERT INTO `JHF_LEVERAGE_GROUP` VALUES
('111111111','A001','USD/JPY','CS0001','0','1',NOW(),NOW())








SHOW CREATE TABLE JHF_CUSTOMER


SELECT * FROM JHF_CUSTOMER_STATUS WHERE LOGIN_ID LIKE '%Tst%';

SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID ='90010002';
SELECT GROUP_ID FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID ='90010002';
SELECT * FROM JHF_CUSTOMER WHERE CUSTOMER_ID LIKE '%ê€÷™±h%';
SELECT * FROM JHF_CUSTOMER WHERE CUSTOMER_ID ='90010002'




-- COUNT THE TEST  DADA  LIKE   9001%
SELECT count( *) FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID like '9001%';
SELECT count( *) FROM JHF_CUSTOMER WHERE CUSTOMER_ID like '9001%';
SELECT count( *) FROM JHF_CUST_BANK_ACCOUNT WHERE CUSTOMER_ID like '9001%' ;
SELECT count( *) FROM JHF_MAIL_ADDRESS WHERE CUSTOMER_ID like '9001%' ;
SELECT count( *) FROM JHF_PERSONAL WHERE CUSTOMER_ID like '9001%' ;
SELECT count( *) FROM JHF_CASH_BALANCE WHERE CUSTOMER_ID like '9001%' ;
SELECT count( *) FROM JHF_CUSTOMER_LOCK WHERE CUSTOMER_ID like '9001%' ;
SELECT count( *) FROM JHF_MAIL_ACTION_MAP WHERE CUSTOMER_ID like '9001%' ;
SELECT count( *) FROM JHF_LEVERAGE_GROUP WHERE CUSTOMER_ID like '9001%' ;
SELECT count( *) FROM JHF_ORDER_NO_GENERATOR WHERE CUSTOMER_ID like '9001%' ;


-- DELETE THE TEST  DADA  LIKE   9001%
DELETE FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID like '9001%';
DELETE FROM JHF_CUSTOMER WHERE CUSTOMER_ID like '9001%';
DELETE FROM JHF_CUST_BANK_ACCOUNT WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_MAIL_ADDRESS WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_PERSONAL WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_CASH_BALANCE WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_CUSTOMER_LOCK WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_MAIL_ACTION_MAP WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_LEVERAGE_GROUP WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_ORDER_NO_GENERATOR WHERE CUSTOMER_ID like '9001%' ;



DELETE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_ALIVE_EXECUTION WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID like '9001%' ;



SELECT * FROM JHF_GROUP_PRODUCT_BAND LIMIT 1;

SELECT * FROM JHF_GROUP_PRODUCT_BAND WHERE GROUP_ID='DEFAULT';


--  FRONT SQL
SELECT DISTINCT(A.CURRENCY_PAIR),
 A.CURRENCY_DECIMAL, 
 A.CURRENCY_ROUND,
 A.CONTRACT_CURRENCY_CODE, 
 A.DISPLAY_SORT_ORDER, 
 A.CURRENCY_PAIR_NAME, 
 A.COUNTER_CURRENCY_CODE, 
 A.WHO_USE, 
 A.DEALER_CURRENCY_DECIMAL, 
 A.DEALER_CURRENCY_ROUND, 
 A.USABLE_FLAG, 
 A.SWAP_UNIT,
 A.INPUT_STAFF_ID, 
 A.UPDATE_STAFF_ID ,
 A.ACTIVE_FLAG, 
 A.INPUT_DATE, 
 A.UPDATE_DATE, 

 A.CURRENCY_PAIR_NAME_HALF   

 FROM JHF_CURRENCY_PAIR A, JHF_GROUP_PRODUCT_BAND B,JHF_CUSTOMER_STATUS C    
 WHERE C.CUSTOMER_ID = '90010002'   
 AND B.GROUP_ID = C.GROUP_ID   
 AND A.CURRENCY_PAIR = B.CURRENCY_PAIR 
 AND A.ACTIVE_FLAG = 1
 AND B.ACTIVE_FLAG = 1
 AND C.ACTIVE_FLAG = 1 
 AND A.usable_Flag = 1 
 AND ( A.WHO_USE = 1 
 OR    A.WHO_USE = 3)  
 ORDER BY A.DISPLAY_SORT_ORDER ASC


SELECT * FROM JHF_GROUP WHERE GROUP_ID = 'DEFAULT';

INSERT INTO JHF_GROUP(GROUP_ID, GROUP_NAME, START_DATE, END_DATE, OPEN_COMMISSION, SETTLE_COMMISSION, DAY_TRADE_SETTLE_COMMISSION, NOTICE_RATIO, ALERT_RATIO, LOSSCUT_WARN_RATIO, LOSSCUT_RATIO, MAX_QUANTITY, OPEN_OVER_AMOUNT_COMMISSION, OPEN_OVER_AMOUNT, SETTLE_OVER_AMOUNT_COMMISSION, SETTLE_OVER_AMOUNT, PRACTICE_LOSSCUT_RATIO, CASH_BACK, INPUT_STAFF_ID, UPDATE_STAFF_ID, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE)
  VALUES('DEFAULT', 'DEFAULT', NULL, NULL, 0.00, 0.00, 0.00, 2.0000, 0.7500, 0.6000, 0.1100, 500, 0.00, 0.00, 0.00, 0.00, NULL, 0.00, 'system', 'system', 1, '2007-02-28 16:11:51.0', '2009-05-21 11:01:35.0');



SELECT concat(LOGIN_ID ,' =111111111111') ,CUSTOMER_ID FROM JHF_CUSTOMER_STATUS WHERE LOGIN_ID LIKE 'Tst%' LIMIT 100 ;

SELECT * FROM JHF_CUSTOMER_STATUS WHERE LOGIN_ID = 'Tst00001'
;
DELETE FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '90010000'


SELECT ORDER_ID,CUSTOMER_ID FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID LIKE '9001%'



---==

mysql -h10.4.9.85 -uMAIN -pPrG7lv2Y -A MAIN

SELECT * FROM JHF_CASH_BALANCE WHERE CUSTOMER_ID LIKE '9001%' ;
SELECT * FROM JHF_CASH_BALANCE WHERE CUSTOMER_ID ='90010008' ;

UPDATE  `JHF_CASH_BALANCE` SET CASH_BALANCE = 999999999999  WHERE CUSTOMER_ID = 90010000


SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '90010000' ORDER BY INPUT_DATE ;
SELECT * FROM JHF_ALIVE_ORDER ORDER BY INPUT_DATE DESC LIMIT 1;

SELECT CUSTOMER_ID,COUNT(*) FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID like '9001%' GROUP BY CUSTOMER_ID;
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID like '9001%' ;
SELECT COUNT(*) FROM JHF_ALIVE_EXECUTION WHERE CUSTOMER_ID like '9001%' ;
SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID like '9001%' ;
SELECT COUNT(*) FROM  JHF_SYS_POSITION_INSERT ;
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE  ORDER_STATUS = 3 ;
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE  ORDER_STATUS <> 3 ;
SELECT customer_id FROM JHF_ALIVE_ORDER group by CUSTOMER_ID;


SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID like '9001%' AND ORDER_STATUS <> 3 ;
SELECT count(*) FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID like '9001%' AND ORDER_STATUS = 3 GROUP BY CUSTOMER_ID;

DELETE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_ALIVE_EXECUTION WHERE CUSTOMER_ID like '9001%' ;
DELETE FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID like '9001%' ;


/usr/local/mysql/bin/mysql MAIN -e "truncate JHF_ALIVE_CONTRACT;"
/usr/local/mysql/bin/mysql MAIN -e "truncate JHF_ALIVE_EXECUTION;"
/usr/local/mysql/bin/mysql MAIN -e "truncate JHF_ALIVE_ORDER;"
/usr/local/mysql/bin/mysql MAIN -e "truncate JHF_CUSTOMER_SESSION;"
/usr/local/mysql/bin/mysql MAIN -e "truncate JHF_SYS_POSITION_INSERT;"

truncate JHF_ALIVE_CONTRACT;
truncate JHF_ALIVE_EXECUTION;
truncate JHF_ALIVE_ORDER;
truncate JHF_CUSTOMER_SESSION;
truncate JHF_SYS_POSITION_INSERT;


SELECT * FROM JHF_APPLICATION_DATE;

SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'USD/JPY'

SELECT * FROM JHF_CUSTOMER_SESSION

SELECT * FROM JHF_PRODUCT WHERE PRODUCT_ID = 'H001' AND CURRENCY_PAIR = 'USD/JPY'

select * from JHF_GROUP_PRODUCT_BAND where GROUP_ID = 'DEFAULT' AND CURRENCY_PAIR = 'USD/JPY'

SELECT GROUP_ID FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '90010000'