

SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '90000088';


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'SYSTEM'


SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE CASHFLOW_SOURCE_ID IN (

    SELECT EXECUTION_ID FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800000602' ));

SELECT * FROM JHF_UNREALIZED_CASHFLOW  WHERE CASHFLOW_TYPE = 6 ORDER BY INPUT_DATE DESC;


SELECT * FROM JHF_CONTRACT_BIND WHERE EXECUTION_ID IN (SELECT EXECUTION_ID FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800000602' ));

SELECT * FROM JHF_SYS_POSITION_INSERT WHERE POSITION_SOURCE_ID IN (SELECT EXECUTION_ID FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800000602' ));


SELECT ORDER_ID,EXECUTION_ID,COMMISSION FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800000602' );


SELECT ORDER_ID ,TRADE_TYPE FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800000601'