

SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '90000088';


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'SYSTEM'


--===================================================

SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE CASHFLOW_SOURCE_ID IN (

    SELECT EXECUTION_ID FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800001006' ));

--SELECT * FROM JHF_UNREALIZED_CASHFLOW  WHERE CASHFLOW_TYPE = 6 ORDER BY INPUT_DATE DESC;


SELECT * FROM JHF_CONTRACT_BIND WHERE EXECUTION_ID IN (SELECT EXECUTION_ID FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800001006' ));

SELECT * FROM JHF_SYS_POSITION_INSERT WHERE POSITION_SOURCE_ID IN (SELECT EXECUTION_ID FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800001006' ));


SELECT ORDER_ID,EXECUTION_ID,COMMISSION FROM JHF_EXECUTION WHERE ORDER_ID IN (
        SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800001006' );


SELECT CONTRACT_ID,ORDER_ID,FORCE_RELATION_ID, SETTLEMENT_COMMISSION,OPEN_COMMISSION FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID IN (
    SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800001406' );

SELECT ORDER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800001006' 

SELECT * FROM JHF_FINISHED_CONTRACT WHERE ORDER_ID = '20090318ORD00001806';


--SELECT ORDER_ID ,TRADE_TYPE FROM JHF_ALIVE_ORDER WHERE ORDER_BIND_ID ='2009031800000901';

--SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'USD/JPY' AND LEVERAGE_LEVEL_ID = ;


show create table JHF_PRODUCT ;


--============

SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'USD/JPY';

UPDATE JHF_PRODUCT SET LOSSCUT_COMMISSION = LEVERAGE_LEVEL_ID WHERE CURRENCY_PAIR = 'USD/JPY';

