SELECT * FROM JHF_CS_OPERATOR WHERE LOGIN_ID = 'admin';



-- QUERY PARENT MENU
SELECT PARENT_MENU_SEQ,PARENT_MENU_NAME,PARENT_MENU_IMG,DISPLAY_ORDER FROM JHF_CS_PARENT_MENU WHERE ACTIVE_FLAG = '1'  ORDER BY DISPLAY_ORDER ;


-- QUERY SON MENU


SELECT * FROM  JHF_CS_GROUP_MENUS AS GM , JHF_CS_GROUP_AUTHORITY AS GA , JHF_CS_PARENT_MENU AS GP 
WHERE GM.SON_MENU_SEQ = GA.SON_MENU_SEQ AND GP.PARENT_MENU_SEQ =GM.PARENT_MENU_SEQ 
AND GM.PARENT_MENU_SEQ = (SELECT DISTINCT PARENT_MENU_SEQ FROM JHF_CS_GROUP_MENUS WHERE INSTR(SON_MENU_URL,'swapInfoInit.do') > 0
                                AND ACTIVE_FLAG = 1   )   
AND GA.CS_GROUP_ID = 1 AND GA.SELECTED_FLAG = 1 
AND GA.ACTIVE_FLAG = 1 AND GM.ACTIVE_FLAG = 1 AND GP.ACTIVE_FLAG = 1  ORDER BY GM.DISPLAY_ORDER ASC ;






--- 1    SELECT PARENT MENU SEQ  ==>  0001

SELECT DISTINCT PARENT_MENU_SEQ FROM JHF_CS_GROUP_MENUS WHERE INSTR(SON_MENU_URL,'swapInfoInit.do') > 0 AND ACTIVE_FLAG = 1  

--- 2    


SELECT * FROM JHF_CS_PARENT_MENU



SELECT * FROM JHF_CS_GROUP_MENUS;
SELECT * FROM JHF_CS_GROUP_AUTHORITY;



CREATE TABLE JHF_CS_GROUP ( 
	CS_GROUP_ID    	decimal(2,0) NOT NULL,
	CS_GROUP_NAME  	varchar(50) NULL,
	INPUT_STAFF_ID 	varchar(6) NULL,
	UPDATE_STAFF_ID	varchar(6) NULL,
	ACTIVE_FLAG    	decimal(1,0) NULL,
	INPUT_DATE     	timestamp NULL,
	UPDATE_DATE    	timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP 
	);











