SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000101' OR CUSTOMER_ID = '00003242' ORDER BY INPUT_DATE DESC;
DELETE FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000101' AND CURRENCY_PAIR = 'USD/JPY';
DELETE FROM JHF_ALIVE_ORDER WHERE ORDER_ID ='20080818ORD00000402';
UPDATE JHF_ALIVE_ORDER SET CUSTOMER_ORDER_NO = 

SELECT * FROM JHF_ORDER_BIND WHERE ORDER_ID = '20080818ORD00000002';


SELECT * FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID = '20080818ORD00000002'




SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'EUR/JPY'


SELECT SP_MODE FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY';

UPDATE JHF_STATUS_CONTRL SET SP_MODE = 1 WHERE CURRENCY_PAIR = 'USD/JPY';



SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID =  '00000101';
SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID =  '00003242';

UPDATE JHF_CUSTOMER_STATUS SET LOGIN_ID = 'I3800001' ,LOGIN_PASSWORD = 'bc177a7a9c7df69c248647b4dfc6fd84'  WHERE CUSTOMER_ID =  '00003242';




SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID in( '00000101','00003242');
SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000101' AND ORDER_ID LIKE '%LUBQ%' ORDER BY INPUT_DATE DESC ;
SELECT * FROM JHF_EXECUTION WHERE ORDER_ID = '20080902ORD00003803';


SELECT ORDER_ID FROM JHF_EXECUTION WHERE EXECUTION_ID = '20080901CUEX00003811';
SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE CASHFLOW_SOURCE_ID = '20080902CUEX00004403';
SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE CASHFLOW_SOURCE_ID = '20080901CUEX00003811';
SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00000101' ORDER BY INPUT_DATE DESC ;



UPDATE JHF_ALIVE_ORDER SET ORDER_STATUS = 1 WHERE ORDER_ID = '00000101LUBQ0000001';
UPDATE JHF_ALIVE_ORDER SET ORDER_STATUS = 9 WHERE ORDER_ID = '20080819ORD00002207';


SELECT * FROM JHF_ORDER_BIND WHERE ORDER_ID = '20080818ORD00001319';

SELECT * FROM JHF_ORDER_BIND WHERE ORDER_BIND_ID = '2008081800001328';



-- DELETE CUSTOMER    [order, contract, execution ,finish order ]

DELETE FROM JHF_ALIVE_ORDER  WHERE CUSTOMER_ID = '00000101';
DELETE FROM JHF_FINISHED_ORDER  WHERE CUSTOMER_ID = '00000101';

DELETE FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID = '00000101';
DELETE FROM JHF_EXECUTION WHERE CUSTOMER_ID = '00000101';




DELETE FROM JHF_ALIVE_ORDER  WHERE CUSTOMER_ID = '00003242';
DELETE FROM JHF_FINISHED_ORDER  WHERE CUSTOMER_ID = '00003242';

DELETE FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID = '00003242';
DELETE FROM JHF_EXECUTION WHERE CUSTOMER_ID = '00003242';



SELECT AUTOHEDGE_SWATICH FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY');


---  stay position
UPDATE JHF_STATUS_CONTRL SET AUTOHEDGE_SWATICH = 1 ,AUTOHEDGE_MARKET_BUY = 1 ,AUTOHEDGE_MARKET_SELL =1 ,
AUTOHEDGE_LIMIT_BUY = 1 ,AUTOHEDGE_LIMIT_SELL=1 ,AUTOHEDGE_STOP_BUY =1,AUTOHEDGE_LIMIT_SELL =1 ,AUTOHEDGE_LOSSCUT_BUY =1 ,AUTOHEDGE_LOSSCUT_SELL =1  
WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY');



SELECT * FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY');
SELECT CAN_BESTFEED_FLAG FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY');

SELECT  FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY','EUR/USD');
UPDATE JHF_STATUS_CONTRL  SET BEST_FEED_SWATICH = 1 ,BEST_HEDGE_SWATICH = 1 WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY','EUR/USD');

SELECT * FROM JHF_COUNTERPARTY;

UPDATE JHF_COUNTERPARTY SET ACTIVE_FLAG = 0 WHERE COUNTERPARTY_ID = 'SA';


UPDATE JHF_COUNTERPARTY_CURRENCYPAIR SET CAN_BESTHEDGE_FLAG = 1 ,CAN_BESTFEED_FLAG = 1 WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY');




SELECT distinct CUSTOMER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE 'TstORD%'

SELECT count(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE 'TstORD%' and ORDER_STATUS=3 AND CUSTOMER_ID in('00000005','00000006') ORDER BY INPUT_DATE DESC 



SELECT * FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' 
SELECT ORDER_ID ,CUSTOMER_ID,ORDER_BIND_ID FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' ;


SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE  ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS = 3 AND CUSTOMER_ID = '00000101';
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE  ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS = 3 AND CUSTOMER_ID = '00003242';


SELECT * FROM JHF_SYS_POSITION WHERE 

SELECT UNUSUAL_WAIT_TIME FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR  IN ('USD/JPY','EUR/JPY');

truncate JHF_EXECUTION

;

----  DELETE    LAO HUANG   TEST   ORDER 
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID ='00000126';
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_STATUS <> 3 AND CUSTOMER_ID = '00000126';
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_STATUS = 3 AND CUSTOMER_ID = '00000126';

SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000126' ;
SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID ='00000126';

SELECT * FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND CUSTOMER_ID ='00000126';
SELECT * FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00000126'
SELECT COUNT(*) FROM JHF_UNREALIZED_CASHFLOW WHERE CUSTOMER_ID = '00000126'
DELETE FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE 'TstORD%';
DELETE FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE 'TstORD%';

--DELETE FROM JHF_ORDER_BIND WHERE ORDER_ID LIKE 'TstORD%';

DELETE FROM JHF_EXECUTION WHERE ORDER_ID LIKE 'TstORD%';
SELECT * FROM JHF_EXECUTION 
DELETE FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID LIKE 'TstORD%';

SELECT * FROM JHF_SYS_POSITION_INSERT 
SELECT * FROM JHF_SYS_POSITION_INSERT_HIS 

SELECT * FROM JHF_HEDGE_CUSTTRADE WHERE ID = '20080828CUEX00001069'



----  DELETE     LU BAO QIANG  TEST   ORDER


DELETE FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '20080820ORD00002805';
DELETE FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%';
DELETE FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%';

--DELETE FROM JHF_ORDER_BIND WHERE ORDER_ID LIKE '%LUBQ%';

DELETE FROM JHF_EXECUTION WHERE ORDER_ID LIKE '%LUBQ%';

DELETE FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID LIKE '%LUBQ%';

DELETE FROM JHF_SYS_POSITION_INSERT;
--DELETE FROM JHF_SYS_POSITION_INSERT_HIS;
DELETE FROM JHF_HEDGE_CUSTTRADE ;


TRUNCATE JHF_ALIVE_CONTRACT
----  OPM SETTLE  ORDER 

SELECT * FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND CUSTOMER_ID = '00000101';


SELECT * FROM JHF_CURRENCY_PAIR WHERE WHO_USE = 3





---  SETTTLE ORDER
SELECT ORDER_ID,TRADE_TYPE ,TOP_ORDER_ID FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '00000101' ORDER BY INPUT_DATE DESC ;
SELECT * FROM JHF_ALIVE_CONTRACT WHERE CUSTOMER_ID = '00000101' AND AMOUNT_NO_SETTLED > 0 ;



SELECT * FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID IN ('20080905CONT00007309','','','');
SELECT * FROM JHF_ALIVE_ORDER WHERE EXECUTION_TYPE = 12 ;


SELECT * FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%';
UPDATE JHF_ALIVE_ORDER SET ORDER_STATUS = 1 WHERE ORDER_ID = '00000101LUBQ0000004';

SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS = 7;
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS = 3;

SELECT ORDER_ID ,ORDER_STATUS ,CUSTOMER_ORDER_NO,CUSTOMER_ID FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%';
SELECT CONTRACT_ID,ORDER_ID,AMOUNT_NO_SETTLED,AMOUNT_SETTLED,AMOUNT_SETTLING,AMOUNT FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID = '00000101LUBQ0000001';
SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%' AND AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING=0  AND CUSTOMER_ID = '00000101';


SELECT COUNT(*) FROM JHF_PRODUCT;

SHOW CREATE TABLE JHF_PRODUCT


--UPDATE JHF_ALIVE_ORDER SET ORDER_STATUS = 7 WHERE 
SELECT * FROM JHF_HEDGE_CUSTTRADE ORDER BY INPUT_DATE DESC;
SELECT * FROM JHF_EXECUTION WHERE ORDER_ID = '00000101LUBQ0002681';
SELECT * FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID = '00000101LUBQ0002681'


SELECT * FROM JHF_ALIVE_ORDER WHERE ORDER_ID = '20080910ORD00030301';
