SELECT * FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE 
SELECT JC.COUNTERPARTY_ID FROM JHF_COUNTERPARTY_CURRENCYPAIR JCC,JHF_COUNTERPARTY JC where 
JCC.COUNTERPARTY_ID = JC.COUNTERPARTY_ID AND JC.RUNING_STATUS = 1 GROUP BY COUNTERPARTY_ID;
;
SELECT * FROM JHF_CURRENCY_PAIR

update JHF_COUNTERPARTY set RUNING_STATUS = 1  where COUNTERPARTY_ID='CTTS';