 select PRODUCT_ID,CURRENCY_PAIR from JHF_GROUP_PRODUCT_BAND where GROUP_ID = 'DEFAULT' and ACTIVE_FLAG = 1 and CURRENCY_PAIR = 'USD/JPY'

select * from JHF_PRODUCT where ACTIVE_FLAG = 1 and USABLE_FLAG = 1 and CURRENCY_PAIR = 'USD/JPY'
=====================
select PRODUCT_ID,CURRENCY_PAIR from JHF_GROUP_PRODUCT_BAND where GROUP_ID = 'DEFAULT' and ACTIVE_FLAG = 1 and CURRENCY_PAIR = 'USD/CAD'
S029           USD/CAD
 select * from JHF_PRODUCT where ACTIVE_FLAG = 1 and USABLE_FLAG = 1 and CURRENCY_PAIR = 'USD/CAD' 