

SELECT COUNT(*) FROM JHF_SPOT_RATE

SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_MOCK
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_DB;

TRUNCATE TABLE JHF_CP_SPOT_RATE_MOCK ;


TRUNCATE TABLE JHF_SPOT_RATE


SELECT * FROM JHF_SPOT_RATE WHERE SPOT_RATE_ID LIKE '20091125%' ORDER BY INPUT_DATE DESC LIMIT 10\G;

update UNIQUE_ID_GENERATOR set MAX_COUNT=9999999999999 where CONTEXT_ID = 'SPOT' 