
---- Ratemanger bugrate check   flag

SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE= 'BUGTICK' AND PROPERTY_KEY =  'RATEMANAGER' ;
UPDATE JHF_APP_PROPERTY SET PROPERTY_VALUE = 1 WHERE PROP_TYPE= 'BUGTICK' AND PROPERTY_KEY =  'RATEMANAGER' ;

-----------------------------
------------ INFO -----------
-----------------------------


SELECT COUNT(*) FROM JHF_SPOT_RATE;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_MOCK;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_DB;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_BC;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_MC;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_CS;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_GS;


TRUNCATE TABLE  JHF_SPOT_RATE;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_MOCK;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_DB;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_BC;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_MC;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_CS;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_GS;


SELECT * FROM Jhf_MA





-----------------------------
------------ MAIN -----------
-----------------------------

SELECT JCC.COUNTERPARTY_ID FROM JHF_COUNTERPARTY_CURRENCYPAIR JCC,JHF_COUNTERPARTY JC

WHERE JCC.COUNTERPARTY_ID = JC.COUNTERPARTY_ID GROUP BY JCC.COUNTERPARTY_ID;







SELECT * FROM JHF_CURRENCY_PAIR WHERE CURRENCY_PAIR = 'EUR/JPY'


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'RATE' AND PROPERTY_KEY = ''


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'BUGTICK' AND PROPERTY_KEY = 'RATEMANAGER';

UPDATE JHF_APP_PROPERTY SET PROPERTY_VALUE = 1 WHERE  PROP_TYPE = 'BUGTICK' AND PROPERTY_KEY = 'RATEMANAGER';
PROPERTY_VALUE





SELECT * FROM JHF_COUNTERPARTY WHERE COUNTERPARTY_ID = 'MOCK'

SELECT * FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE COUNTERPARTY_ID = 'MOCK'

update JHF_COUNTERPARTY set PB_SB_FLAG = 2 where COUNTERPARTY_ID <> 'MOCK';

SELECT * FROM  JHF_HEDGER_MODE
COUNTERPARTY_NAME


