

SELECT COUNT(*) FROM JHF_SPOT_RATE




RATEMANGER
-- 根据 frontdate ，查询 JHF_SPOT_RATE，
-- 1。如果存在，取当日jhf_spot_rate的最后一个汇率 构造FxSpotRateInfo
-- 2。如果不存在 
-- // 根据上一日的jhf_daily_rate_summary的close rate构造FxSpotRateInfo
--            // 如果来一条新的汇率需要更新openRate的值
SELECT * FROM JHF_SPOT_RATE





-- ratemanager启动会读取 JHF_CP_SPOT_RATE_X  表的历史汇率 （取最后一条） ，然后构造CpSpotRate

SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_MOCK
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_DB;




TRUNCATE TABLE JHF_CP_SPOT_RATE_MOCK ;
TRUNCATE TABLE JHF_CP_SPOT_RATE_DB;



-- 如果JHF_CP_SPOT_RATE_X 表 ，没有数据，   则查询JHF_CP_DAILY_RATE_SUMMARY



TRUNCATE TABLE JHF_SPOT_RATE


SELECT * FROM JHF_SPOT_RATE WHERE SPOT_RATE_ID LIKE '20091125%' ORDER BY INPUT_DATE DESC LIMIT 10\G;

update UNIQUE_ID_GENERATOR set MAX_COUNT=9999999999999 where CONTEXT_ID = 'SPOT' 








--   
SELECT * FROM JHF_CURRENCY_PAIR where WHO_USE in(3 ,1) AND CURRENCY_PAIR IN( 'AUD/NZD','AUD/CHF','AUD/CAD','EUR/AUD','CAD/CHF')


---  

SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'RATE' AND PROPERTY_KEY = 'rateSendMinTime' ;

UPDATE JHF_APP_PROPERTY SET PROPERTY_VALUE = 1000 WHERE  PROP_TYPE = 'RATE' AND PROPERTY_KEY = 'rateSendMinTime' ;

-- 
SELECT * FROM JHF_COUNTERPARTY WHERE  RUNING_STATUS = 1 AND COUNTERPARTY_ID IN ( 'MOCK','DB') 

SELECT * FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE CURRENCY_PAIR = 'USD/JPY'

SELECT CURRENCY_PAIR,BEST_FEED_TYPE, BESTFEED_USEUNCHECKCP_WHEN_CHECKEDCPNG FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR IN ('USD/JPY','GBP/JPY')

