

SELECT COUNT(*) FROM JHF_SPOT_RATE

SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_MOCK
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_DB;

TRUNCATE TABLE JHF_CP_SPOT_RATE_MOCK ;


TRUNCATE TABLE JHF_SPOT_RATE

