
---- Ratemanger bugrate check   flag

SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE= 'BUGTICK' AND PROPERTY_KEY =  'RATEMANAGER' ;
UPDATE JHF_APP_PROPERTY SET PROPERTY_VALUE = 1 WHERE PROP_TYPE= 'BUGTICK' AND PROPERTY_KEY =  'RATEMANAGER' ;

-----------------------------
------------ INFO -----------
-----------------------------


SELECT COUNT(*) FROM JHF_SPOT_RATE;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_MOCK;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_DB;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_BC;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_MC;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_CS;
SELECT COUNT(*) FROM JHF_CP_SPOT_RATE_GS;


TRUNCATE TABLE  JHF_SPOT_RATE;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_MOCK;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_DB;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_BC;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_MC;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_CS;
TRUNCATE TABLE  JHF_CP_SPOT_RATE_GS;


SELECT CURRENCY_PAIR FROM JHF_DAILY_RATE_SUMMARY GROUP BY CURRENCY_PAIR;





-----------------------------
------------ MAIN -----------
-----------------------------

--  RATEMANGER     QUERY   JHF_COUNTERPARTY_CURRENCYPAIR   JHF_COUNTERPARTY   FOR INIT
SELECT JCC.CURRENCY_PAIR,   JCC.COUNTERPARTY_ID  ,JCC.FEED_PRIORTIY 
FROM JHF_COUNTERPARTY_CURRENCYPAIR JCC,JHF_COUNTERPARTY JC 

WHERE JCC.COUNTERPARTY_ID = JC.COUNTERPARTY_ID 
AND JC.RUNING_STATUS = 1 AND JC.ACTIVE_FLAG =1 AND JCC.ACTIVE_FLAG =1 
ORDER BY JCC.CURRENCY_PAIR,JCC.FEED_PRIORTIY ;


--  RATEMANGER    IF  INFO DB IS STILL WORK   QUERY  INFO. JHF_CP_SPOT_RATE_xxxx        with  FRONT_DATE ,CURRENCY_PAIR


--  RATEMANGER    IF  INFO DB IS DOWN         QUERY  MAIN. JHF_CP_DAILY_RATE_SUMMARY     with  COUNTERPARTY_ID,RATE_DATE ,CURRENCY_PAIR






SELECT * FROM JHF_CURRENCY_PAIR WHERE CURRENCY_PAIR = 'EUR/JPY'


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'RATE' AND PROPERTY_KEY = ''


SELECT * FROM JHF_APP_PROPERTY WHERE PROP_TYPE = 'BUGTICK' AND PROPERTY_KEY = 'RATEMANAGER';

UPDATE JHF_APP_PROPERTY SET PROPERTY_VALUE = 1 WHERE  PROP_TYPE = 'BUGTICK' AND PROPERTY_KEY = 'RATEMANAGER';
PROPERTY_VALUE





SELECT * FROM JHF_COUNTERPARTY WHERE COUNTERPARTY_ID = 'MOCK'

SELECT * FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE COUNTERPARTY_ID = 'MOCK'

update JHF_COUNTERPARTY set PB_SB_FLAG = 2 where COUNTERPARTY_ID <> 'MOCK';

SELECT * FROM  JHF_HEDGER_MODE
COUNTERPARTY_NAME





SELECT * FROM JHF_APPLICATION_DATE



SELECT  FROM JHF_COUNTERPARTY WHERE COUNTERPARTY_ID IN( 'MOCK','DB');
SELECT * FROM JHF_CURRENCY_PAIR WHERE WHO_USE = 

UPDATE JHF_COUNTERPARTY SET RUNING_STATUS = 1 WHERE COUNTERPARTY_ID = 'DB'

//如果是manual汇率不进行处理  (3#)              ,change to  1#
SELECT PRI_FEED_SRC_TYPE FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR ='USD/JPY' ;
UPDATE JHF_STATUS_CONTRL SET PRI_FEED_SRC_TYPE = 1 WHERE CURRENCY_PAIR ='USD/JPY' ;


SELECT * FROM JHF_STATUS_CONTRL WHERE PRI_FEED_SRC_TYPE = 3

SELECT * FROM JHF_COUNTERPARTY_CURRENCYPAIR
;


---  ratemanager init  countparty  ==> Cp-Destination.xml

select jcc.CURRENCY_PAIR ,jcc.COUNTERPARTY_ID ,jcc.FEED_PRIORTIY  
from JHF_COUNTERPARTY_CURRENCYPAIR as jcc ,JHF_COUNTERPARTY as jc 
  where jc.COUNTERPARTY_ID = jcc.COUNTERPARTY_ID 
			 and  jc.RUNING_STATUS = 1 
			 and jc.ACTIVE_FLAG= 1
			 and jcc.ACTIVE_FLAG =1
			  GROUP BY COUNTERPARTY_ID  order by jcc.CURRENCY_PAIR ,jcc.FEED_PRIORTIY;



UPDATE JHF_COUNTERPARTY_CURRENCYPAIR SET ACTIVE_FLAG = 0  WHERE COUNTERPARTY_ID = 'CS' 

SELECT * FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE COUNTERPARTY_ID IN ('MOCK','DB','GS')

SELECT * FROM JHF_COUNTERPARTY  WHERE COUNTERPARTY_ID IN ('SG')
UPDATE JHF_COUNTERPARTY SET  ACTIVE_FLAG = 0  WHERE COUNTERPARTY_ID IN ('SG','ODL','WLCM','AG','GKGOH')



----  ratemanager   who use

SELECT * FROM JHF_CURRENCY_PAIR WHERE CURRENCY_PAIR = 'USD/CHF'

SELECT * FROM JHF_CURRENCY_PAIR WHERE WHO_USE = 3 ;

UPDATE JHF_CURRENCY_PAIR SET ACTIVE_FLAG = 0  WHERE CURRENCY_PAIR NOT IN (
'AUD/JPY',
'CAD/JPY',
'CHF/JPY',
'EUR/JPY',
'EUR/USD',
'GBP/JPY',
'GBP/USD',
'NZD/JPY',
'USD/JPY',
'ZAR/JPY'
);

SELECT CURRENCY_PAIR FROM JHF_CURRENCY_PAIR  GROUP BY CURRENCY_PAIR

SELECT CURRENCY_PAIR FROM JHF_DAILY_RATE_SUMMARY GROUP BY CURRENCY_PAIR;




