		sb.append(" SELECT CUSTOMER_ID ");
		sb.append(" FROM JHF_CUSTOMER_STATUS    ");
		sb.append(" WHERE RISK_ACCOUNT_STATUS = "+RiskAccountStatus.NORMAL.getStatus());
		sb.append(" AND RISK_CONTROL_STATUS = "+RiskControlStatus.VALID.getStatus());
		sb.append(" AND RISK_CONTROL_ACTIVE_FLAG ="+RiskControlActiveFlag.VALID.getFlag());
		sb.append(" AND RISK_CONTROL_CONSTRANT = "+ConstraintTypeEnum.TYPE_ENABLE_ALL_ENUM.getValue());
		sb.append(" AND (  (RISK_CONTROL_PROFIT_FLAG = "+RiskControlProfitFlagEnum.VALID.getFlag());
		sb.append("		     AND RISK_CONTROL_PROFIT_VALUE <= ?   ");
		sb.append("         ) ");
		sb.append("      OR   ");
		sb.append("         (RISK_CONTROL_LOSS_FLAG = "+RiskControlLossFlagEnum.VALID.getFlag());
		sb.append("          AND RISK_CONTROL_LOSS_VALUE >=   ?   ");
		sb.append("         ) ");
		sb.append("      )" );
		sb.append(" AND ACTIVE_FLAG =1");
		sb.append(" AND CUSTOMER_ID=?");