SELECT * FROM JHF_CUSTTRADE_CONTRL WHERE




 SELECT CURRENCY_PAIR,INSTANT_SLIP_CONFIG_TYPE,LOSSCUT_SLIP_CONFIG_TYPE,INSTANT_SLIP_CONFIG_TYPE_2,UPDATE_DATE 
FROM JHF_CUSTTRADE_CONTRL 
WHERE (INSTANT_SLIP_CONFIG_TYPE < 1 AND INSTANT_PRICE_SWATICH IN (3 ,4))
 OR( LOSSCUT_SLIP_CONFIG_TYPE < 1 AND LOSSCUT_PRICE_SWATICH IN (3,4))
OR (INSTANT_SLIP_CONFIG_TYPE_2 < 1 AND  INSTANT_PRICE_SWATICH_2 IN (3,4));


