


SELECT * FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY';


SELECT INSTANT_1_CLOSE_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;



SELECT INSTANT_1_OPEN_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 2 ;


SELECT INSTANT_1_OPEN_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 2 ;



SELECT STOP_CLOSE_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 2 ;







SELECT * FROM JHF_STATUS_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY';


SELECT INSTANT_1_CLOSE_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;



SELECT INSTANT_1_OPEN_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 2 ;


SELECT INSTANT_2_OPEN_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;

SELECT INSTANT_2_CLOSE_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;


SELECT LIMIT_OPEN_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;

SELECT LIMIT_CLOSE_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;

SELECT STOP_OPEN_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 2 ;

SELECT LOSSCUT_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 1 ;

SELECT LOSSCUT_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 2 ;



SELECT RISKCONTROL_STAY_PLACE FROM JHF_CUSTTRADE_CONTRL WHERE CURRENCY_PAIR = 'USD/JPY' AND CUSTTRADE_BAND = 3 ;
