
SELECT * FROM JHF_UNREALIZED_CASHFLOW 
    WHERE CUSTOMER_ID = '90000007' AND CASHFLOW_SOURCE_ID IN (SELECT EXECUTION_ID FROM JHF_ALIVE_EXECUTION WHERE ORDER_ID = '20090722ORD00033611');


SELECT * FROM JHF_ALIVE_CONTRACT_BIND WHERE EXECUTION_ID IN (SELECT EXECUTION_ID FROM JHF_ALIVE_EXECUTION WHERE ORDER_ID = '20090722ORD00033611') ;


SELECT EXECUTION_ID FROM JHF_ALIVE_EXECUTION WHERE ORDER_ID = '20090708ORD00373504' ;



SELECT * FROM JHF_APPLICATION_DATE ;


SELECT * FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND CUSTOMER_ID = '90000007'

UPDATE JHF_ALIVE_CONTRACT SET SWAP_INTEREST='200'  WHERE AMOUNT_NO_SETTLED > 0 AND CUSTOMER_ID = '90000007'

SELECT * FROM JHF_PRODUCT WHERE CURRENCY_PAIR = 'EUR/JPY' 

SELECT * FROM JHF_SWAP_POINT ;

SELECT * FROM 
