
SELECT * FROM JHF_TRADE_CONSTRAINT ;

UPDATE JHF_TRADE_CONSTRAINT 
SET OPEN_BUY_CONSTRAINT = 3,       OPEN_SELL_CONSTRAINT =3,      CLOSE_BUY_CONSTRAINT =3,      CLOSE_SELL_CONSTRAINT =3  ;




UPDATE JHF_TRADE_CONSTRAINT SET MARKET_CLOSE_FLAG = 0 ,
OPEN_BUY_CONSTRAINT = 0,       OPEN_SELL_CONSTRAINT =0,      CLOSE_BUY_CONSTRAINT =0,      CLOSE_SELL_CONSTRAINT =0 ,
 MCUT_COMPUTE_CONSTRAINT = 0  ,LOGIN_CONSTRAINT = 0,DEPOSIT_CONSTRAINT=0 ,WITHDRAWAL_CONSTRAINT=0 ,SWAPGET_CONSTRAINT = 0 
,DL_BUY_CONSTRAINT = 0 ,DL_SELL_CONSTRAINT = 0;



SELECT * FROM JHF_TRADE_CONSTRAINT ;

UPDATE JHF_TRADE_CONSTRAINT SET MARKET_CLOSE_FLAG = 0 ;

UPDATE JHF_TRADE_CONSTRAINT SET MARKET_CLOSE_FLAG = 0 ;


UPDATE JHF_TRADE_CONSTRAINT SET OPEN_BUY_CONSTRAINT = 0 ,OPEN_SELL_CONSTRAINT = 0 ,CLOSE_BUY_CONSTRAINT = 0 ,CLOSE_SELL_CONSTRAINT = 0  ;




