

SELECT * FROM JHF_CUSTOMER WHERE CUSTOMER_ID = '00000014';


UPDATE JHF_CUSTOMER SET ACCOUNT_OPEN_STATUS = 7 WHERE CUSTOMER_ID = '00000014';

SELECT ACCOUNT_ACTIVE_STATUS FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '00000014';

UPDATE JHF_CUSTOMER_STATUS SET ACCOUNT_ACTIVE_STATUS = 0 WHERE CUSTOMER_ID = '00000014';

SELECT * FROM JHF_TRADE_CONSTRAINT

SELECT * FROM JHF_CUSTOMER_STATUS WHERE  CUSTOMER_ID = '00000014';
SELECT * FROM JHF_APPLICATION_DATE

UPDATE JHF_CUSTOMER_STATUS SET OPEN_BUY_CONSTRAINT = 0 , OPEN_SELL_CONSTRAINT = 0  , CLOSE_SELL_CONSTRAINT = 0 ,CLOSE_BUY_CONSTRAINT = 0  WHERE  CUSTOMER_ID = '00000014';

