SELECT CONTRACT_ID,ORDER_ID FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING > 0 AND CUSTOMER_ID = '90012849';


SELECT ORDER_ID,ORDER_BIND_ID,ORDER_STATUS FROM JHF_ALIVE_ORDER WHERE ORDER_ID = '20090813ETO00979820'

SELECT * FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID = '20090813ETO00979820';


SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '90012849' AND ORDER_STATUS = 7




SELECT ORDER_ID,ORDER_BIND_ID,ORDER_STATUS FROM JHF_ALIVE_ORDER WHERE ORDER_ID ='20091125ORD00829801'

SELECT order_id FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING > 0 AND CUSTOMER_ID = '90012849';


SELECT ORDER_ID,ORDER_BIND_ID,CURRENCY_PAIR,SIDE,EXPIRATION_DATE,EXPIRATION_TYPE,ORDER_PRICE,EXECUTION_TYPE,ORDER_STATUS ,UPDATE_DATE,ACTIVE_FLAG FROM JHF_ALIVE_ORDER 
WHERE TOP_ORDER_ID IN (
SELECT order_id FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING > 0 AND CUSTOMER_ID = '90012849'
);

UPDATE JHF_ALIVE_ORDER SET EXPIRATION_TYPE= 3 WHERE TOP_ORDER_ID IN (
SELECT order_id FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING > 0 AND CUSTOMER_ID = '90012849'
);


SELECT * FROM JHF_ALIVE_ORDER WHERE CUSTOMER_ID = '90012849' ORDER BY UPDATE_DATE DESC LIMIT 60



SELECT * FROM JHF_CUSTOMER_STATUS WHERE CUSTOMER_ID = '90012849'

90012849=e10adc3949ba59abbe56e057f20f883e

update JHF_CUSTOMER_STATUS set LOGIN_PASSWORD = 'e10adc3949ba59abbe56e057f20f883e' where CUSTOMER_ID = '90012849'



SELECT * FROM JHF_ALIVE_CONTRACT WHERE AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING > 0 AND CUSTOMER_ID = '90006627';


;
SELECT ORDER_ID,ORDER_BIND_ID,ORDER_STATUS, EXPIRATION_TYPE,EXECUTION_TYPE, INPUT_DATE,UPDATE_DATE FROM JHF_ALIVE_ORDER  WHERE ORDER_STATUS = 1  AND CUSTOMER_ID = '90006627';


SELECT CUSTOMER_ID FROM JHF_ALIVE_ORDER  WHERE ORDER_STATUS = 1 AND EXECUTION_TYPE = 8 GROUP BY CUSTOMER_ID ;


SELECT * FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID = '20091124ORD00828843' 


UPDATE JHF_ALIVE_ORDER SET EXECUTION_TYPE = 0 WHERE ORDER_STATUS = 7 AND EXECUTION_TYPE = 8 AND CUSTOMER_ID = '90006627';
UPDATE JHF_ALIVE_ORDER SET EXPIRATION_TYPE = 3 WHERE ORDER_STATUS = 7  AND CUSTOMER_ID = '90006627';

SELECT * FROM JHF_CUSTOMER_STATUS WHERE LOGIN_ID = 'Ien00263'

UPDATE  

SELECT * FROM JHF_PRODUCT WHERE 

