---  load runner   ## order   ###
DELETE FROM JHF_ALIVE_ORDER WHERE ORDER_ID  IN ('20080711ORD00001635','20080715ORD00000485')

SELECT * FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%';
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%';

SELECT ORDER_ID ,ORDER_STATUS FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%';
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS <> 3
SELECT ORDER_ID ,ORDER_STATUS FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS <> 3 ;
SELECT ORDER_ID ,ORDER_STATUS FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS = 3 ;
SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS = 3 ;

SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%' AND AMOUNT_SETTLING >0  
SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%' AND AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING=0  ;

SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%' AND AMOUNT_NO_SETTLED > 0 AND AMOUNT_SETTLING = 0
SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%' AND AMOUNT_NO_SETTLED = 0 AND AMOUNT_SETTLING = 0
;


SELECT COUNT(*) FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%' AND ORDER_STATUS = 7;

SELECT COUNT(*) FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%' AND AMOUNT_SETTLING >0  ;



SELECT *  FROM MAIN.JHF_ALIVE_ORDER AS JHF 
WHERE JHF.ORDER_STATUS = 7  
AND JHF.ACTIVE_FLAG = 1  
AND 
JHF.UPDATE_DATE < ( now()  - INTERVAL 3 MINUTE );

delete from JHF_ALIVE_ORDER where ORDER_STATUS = 7
SELECT * FROM JHF_SYS_POSITION_INSERT;
TRUNCATE JHF_SYS_POSITION_INSERT;

SELECT * FROM JHF_ALIVE_CONTRACT ORDER BY CONTRACT_ID DESC;

SELECT * FROM JHF_APP_PROPERTY 
UPDATE JHF_APP_PROPERTY SET PROPERTY_VALUE = '' WHERE PROP_TYPE = 'MAIL_ADDRESS' AND PROPERTY_KEY = 'CsMailAddress'
















DELETE FROM JHF_ALIVE_ORDER WHERE ORDER_ID LIKE '%LUBQ%';
DELETE FROM JHF_ALIVE_CONTRACT WHERE ORDER_ID LIKE '%LUBQ%';

--DELETE FROM JHF_ORDER_BIND WHERE ORDER_ID LIKE '%LUBQ%';

DELETE FROM JHF_ALIVE_EXECUTION WHERE ORDER_ID LIKE '%LUBQ%';

DELETE FROM JHF_ORDER_STATUS_HISTORY WHERE ORDER_ID LIKE '%LUBQ%';

DELETE FROM JHF_SYS_POSITION_INSERT;
--DELETE FROM JHF_SYS_POSITION_INSERT_HIS;
--DELETE FROM JHF_HEDGE_CUSTTRADE WHERE ID LIKE '%LUBQ%';

SELECT * FROM JHF_MAIL_ADDRESS WHERE CUSTOMER_ID = '00006701'