



DB初始化数据																
																
1.添加CP CS																
INSERT INTO JHF_COUNTERPARTY 																
(COUNTERPARTY_ID,COUNTERPARTY_TYPE,COUNTERPARTY_SHORT_NAME,COUNTERPARTY_NAME,SWIFT_BIC_CD,OPEN_BUY_CONSTRAINT,OPEN_SELL_CONSTRAINT,CLOSE_BUY_CONSTRAINT,CLOSE_SELL_CONSTRAINT,OPEN_TIME,CLOSE_TIME,RUNING_STATUS,																
 UPDATE_STAFF_ID,INPUT_STAFF_ID,ACTIVE_FLAG,INPUT_DATE,UPDATE_DATE,PB_SB_FLAG,RELATION_PBCP_ID) 																
 VALUES ('CS',2,'CS','CS',null,0,0,0,0,'0600','0600',1,'system','system',1,sysdate(),sysdate(),2,'DB');																
 																
2.添加对应的CP CurrencyPair																
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR(COUNTERPARTY_ID, CURRENCY_PAIR, FEED_PRIORTIY,HEDGE_PRIORTIY,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,																
    SPREAD_ALERT_VALUE, TRADABLE, OPEN_TIME, CLOSE_TIME, UPDATE_STAFF_ID, INPUT_STAFF_ID, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE) 																
SELECT  'CS', CURRENCY_PAIR, 																
        (select max(FEED_PRIORTIY)+1 from JHF_COUNTERPARTY_CURRENCYPAIR), 																
        (select max(HEDGE_PRIORTIY)+1 from JHF_COUNTERPARTY_CURRENCYPAIR),																
		0,0,SPREAD_ALERT_VALUE, TRADABLE, OPEN_TIME, CLOSE_TIME, UPDATE_STAFF_ID, 														
		INPUT_STAFF_ID, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE 														
FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE COUNTERPARTY_ID = 'BC';																
																
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 																
SELECT 'CS',CURRENCY_PAIR,'1',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW() 																
FROM JHF_COUNTERPARTY_CURRENCYPAIR																
WHERE COUNTERPARTY_ID='CS';																
																
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 																
SELECT 'CS',CURRENCY_PAIR,'2',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()																
FROM JHF_COUNTERPARTY_CURRENCYPAIR																
WHERE COUNTERPARTY_ID='CS';																
																
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 																
SELECT 'CS',CURRENCY_PAIR,'3',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE COUNTERPARTY_ID='CS';										
										
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 										
SELECT 'CS',CURRENCY_PAIR,'4',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR WHERE										
COUNTERPARTY_ID='CS';										
										
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 										
SELECT 'CS',CURRENCY_PAIR,'5',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE COUNTERPARTY_ID='CS';										
										
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 										
SELECT 'CS',CURRENCY_PAIR,'6',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE COUNTERPARTY_ID='CS';										
										
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET SELECT 'CS',CURRENCY_PAIR,'7',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE COUNTERPARTY_ID='CS';										
										
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 										
SELECT 'CS',CURRENCY_PAIR,'8',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE COUNTERPARTY_ID='CS';										
										
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 										
SELECT 'CS',CURRENCY_PAIR,'9',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE COUNTERPARTY_ID='CS';										
										
INSERT INTO JHF_COUNTERPARTY_CURRENCYPAIR_SET 										
SELECT 'CS',CURRENCY_PAIR,'10',FEED_PRIORTIY,HEDGE_PRIORTIY,SPREAD_ALERT_VALUE,CAN_BESTHEDGE_FLAG,CAN_BESTFEED_FLAG,TRADABLE,UPDATE_STAFF_ID,INPUT_STAFF_ID,1,NOW(),NOW()										
FROM JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE COUNTERPARTY_ID='CS';										
										
3.添加对应的Hedger Mode										
										
INSERT INTO MAIN.JHF_HEDGER_MODE(COUNTERPARTY_ID, CURRENCY_PAIR, SOURCE_TYPE, TRADE_MODE, ACTIVE_FLAG, 										
     INPUT_DATE, UPDATE_DATE, INPUT_STAFF_ID, UPDATE_STAFF_ID) 										
SELECT 'CS', CURRENCY_PAIR, SOURCE_TYPE, TRADE_MODE, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE, INPUT_STAFF_ID, UPDATE_STAFF_ID 										
     FROM MAIN.JHF_HEDGER_MODE WHERE COUNTERPARTY_ID = 'BC';										
										
4.初始化CP日足,MAIN和INFO都需要执行:										
INSERT INTO JHF_CP_DAILY_RATE_SUMMARY										
SELECT 'CS',CURRENCY_PAIR,RATE_DATE,OPEN_ASK,OPEN_BID,OPEN_PRICE_TIME,OPEN_MID,										
HIGH_ASK,HIGH_BID,HIGH_PRICE_TIME,HIGH_MID,LOW_ASK,LOW_BID,LOW_PRICE_TIME,LOW_MID,CLOSE_ASK,										
CLOSE_BID,CLOSE_PRICE_TIME,CLOSE_MID,ACTIVE_FLAG,INPUT_DATE,UPDATE_DATE,IS_ESTIMATE_CP										
FROM JHF_CP_DAILY_RATE_SUMMARY WHERE COUNTERPARTY_ID='BC';										
										
(注意:执行以下这个SQL,否则,会引起Rollover的异常)										
update JHF_CP_DAILY_RATE_SUMMARY set IS_ESTIMATE_CP='0' where COUNTERPARTY_ID='CS' and IS_ESTIMATE_CP='1';										
										
5.INFO库,创建JHF_CP_SPOT_RATE_CS										
CREATE TABLE `JHF_CP_SPOT_RATE_CS` (										
  `FRONT_DATE` varchar(8) NOT NULL,										
  `CP_SPOT_RATE_ID` varchar(20) NOT NULL,										
  `MESSAGE_TIME` timestamp NULL default NULL,										
  `CURRENCY_PAIR` varchar(7) default NULL,										
  `COUNTERPARTY_ID` varchar(6) default NULL,										
  `JHF_PRICE_ID` varchar(60) default NULL,										
  `ASK_0BD_PRICE_ID` varchar(128) default NULL,										
  `ASK_0BD_TRADEABLE` decimal(1,0) default NULL,										
  `ASK_0BD_RATE` decimal(10,6) default NULL,										
  `ASK_0BD_VALUE_DATE` varchar(8) default NULL,										
  `ASK_0BD_CONTRACT_LOWER_AMOUNT` decimal(15,2) default NULL,										
  `ASK_0BD_CONTRACT_UPPER_AMOUNT` decimal(15,2) default NULL,										
  `ASK_0BD_COUNTER_LOWER_AMOUNT` decimal(17,4) default NULL,										
  `ASK_0BD_COUNTER_UPPER_AMOUNT` decimal(17,4) default NULL,										
  `BID_0BD_PRICE_ID` varchar(128) default NULL,										
  `BID_0BD_TRADEABLE` decimal(1,0) default NULL,										
  `BID_0BD_RATE` decimal(10,6) default NULL,										
  `BID_0BD_VALUE_DATE` varchar(8) default NULL,										
  `BID_0BD_CONTRACT_LOWER_AMOUNT` decimal(15,2) default NULL,										
  `BID_0BD_CONTRACT_UPPER_AMOUNT` decimal(15,2) default NULL,										
  `BID_0BD_COUNTER_LOWER_AMOUNT` decimal(17,4) default NULL,										
  `BID_0BD_COUNTER_UPPER_AMOUNT` decimal(17,4) default NULL,										
  `ASK_1BD_PRICE_ID` varchar(128) default NULL,										
  `ASK_1BD_TRADEABLE` decimal(1,0) default NULL,										
  `ASK_1BD_RATE` decimal(10,6) default NULL,										
  `ASK_1BD_VALUE_DATE` varchar(8) default NULL,										
  `ASK_1BD_CONTRACT_LOWER_AMOUNT` decimal(15,2) default NULL,										
  `ASK_1BD_CONTRACT_UPPER_AMOUNT` decimal(15,2) default NULL,										
  `ASK_1BD_COUNTER_LOWER_AMOUNT` decimal(17,4) default NULL,										
  `ASK_1BD_COUNTER_UPPER_AMOUNT` decimal(17,4) default NULL,										
  `BID_1BD_PRICE_ID` varchar(128) default NULL,										
  `BID_1BD_TRADEABLE` decimal(1,0) default NULL,										
  `BID_1BD_RATE` decimal(10,6) default NULL,										
  `BID_1BD_VALUE_DATE` varchar(8) default NULL,										
  `BID_1BD_CONTRACT_LOWER_AMOUNT` decimal(15,2) default NULL,										
  `BID_1BD_CONTRACT_UPPER_AMOUNT` decimal(15,2) default NULL,										
  `BID_1BD_COUNTER_LOWER_AMOUNT` decimal(17,4) default NULL,										
  `BID_1BD_COUNTER_UPPER_AMOUNT` decimal(17,4) default NULL,										
  `ASK_2BD_PRICE_ID` varchar(128) default NULL,										
  `ASK_2BD_TRADEABLE` decimal(1,0) default NULL,										
  `ASK_2BD_RATE` decimal(10,6) default NULL,										
  `ASK_2BD_VALUE_DATE` varchar(8) default NULL,										
  `ASK_2BD_CONTRACT_LOWER_AMOUNT` decimal(15,2) default NULL,										
  `ASK_2BD_CONTRACT_UPPER_AMOUNT` decimal(15,2) default NULL,										
  `ASK_2BD_COUNTER_LOWER_AMOUNT` decimal(17,4) default NULL,										
  `ASK_2BD_COUNTER_UPPER_AMOUNT` decimal(17,4) default NULL,										
  `BID_2BD_PRICE_ID` varchar(128) default NULL,										
  `BID_2BD_TRADEABLE` decimal(1,0) default NULL,										
  `BID_2BD_RATE` decimal(10,6) default NULL,										
  `BID_2BD_VALUE_DATE` varchar(8) default NULL,										
  `BID_2BD_CONTRACT_LOWER_AMOUNT` decimal(15,2) default NULL,										
  `BID_2BD_CONTRACT_UPPER_AMOUNT` decimal(15,2) default NULL,										
  `BID_2BD_COUNTER_LOWER_AMOUNT` decimal(17,4) default NULL,										
  `BID_2BD_COUNTER_UPPER_AMOUNT` decimal(17,4) default NULL,										
  `ACTIVE_FLAG` decimal(1,0) default NULL,										
  `INPUT_DATE` timestamp NULL default NULL,										
  `UPDATE_DATE` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,										
  PRIMARY KEY  (`FRONT_DATE`,`CP_SPOT_RATE_ID`),										
  KEY `CPSPOT_02` (`CURRENCY_PAIR`,`MESSAGE_TIME`)										
) ENGINE=MyISAM DEFAULT CHARSET=cp932;										
										
6.初始化WhiteLabel 相关的内容,for dmm WhiteLabel										
										
insert into JHF_WLCP_CURRENCYPAIR										
    (CLIENT_ID, COUNTERPARTY_ID, CURRENCY_PAIR, FEED_PRIORTIY, CAN_BESTFEED_FLAG,										
    UPDATE_STAFF_ID, INPUT_STAFF_ID, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE										
    )										
select 'dmm', 'CS', CURRENCY_PAIR,FEED_PRIORTIY, CAN_BESTFEED_FLAG,										
    'SYSTEM', 'SYSTEM', 1, now(), now()										
    from JHF_COUNTERPARTY_CURRENCYPAIR										
WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY','GBP/JPY','AUD/JPY','NZD/JPY','CHF/JPY',										
    'CAD/JPY','ZAR/JPY','EUR/USD','GBP/USD','AUD/USD','NZD/USD') and COUNTERPARTY_ID='CS';										
										
  初始化WhiteLabel 相关的内容,for emfx WhiteLabel										
insert into JHF_WLCP_CURRENCYPAIR										
    (CLIENT_ID, COUNTERPARTY_ID, CURRENCY_PAIR, FEED_PRIORTIY, CAN_BESTFEED_FLAG,										
    UPDATE_STAFF_ID, INPUT_STAFF_ID, ACTIVE_FLAG, INPUT_DATE, UPDATE_DATE										
    )										
select 'emfx', 'CS', CURRENCY_PAIR,FEED_PRIORTIY, CAN_BESTFEED_FLAG,										
    'SYSTEM', 'SYSTEM', 1, now(), now()										
from JHF_COUNTERPARTY_CURRENCYPAIR										
    WHERE CURRENCY_PAIR IN ('USD/JPY','EUR/JPY','GBP/JPY','AUD/JPY','NZD/JPY','CHF/JPY',										
    'CAD/JPY','ZAR/JPY','EUR/USD','GBP/USD','AUD/USD','NZD/USD','EUR/GBP','USD/CAD','USD/CHF','GBP/CHF') and COUNTERPARTY_ID='CS';										
										
										

